package br.com.sicoob_credinova.arquivo_prejuizo_uad.view.documentos;

import br.com.sicoob_credinova.arquivo_prejuizo_uad.controller.CaixaController;
import br.com.sicoob_credinova.arquivo_prejuizo_uad.controller.DocumentoController;
import br.com.sicoob_credinova.arquivo_prejuizo_uad.controller.NomeDosCamposController;
import br.com.sicoob_credinova.arquivo_prejuizo_uad.controller.ValoresDosCamposController;
import br.com.sicoob_credinova.arquivo_prejuizo_uad.enums.Status;
import br.com.sicoob_credinova.arquivo_prejuizo_uad.model.Caixa;
import br.com.sicoob_credinova.arquivo_prejuizo_uad.model.Documento;
import br.com.sicoob_credinova.arquivo_prejuizo_uad.model.NomeDosCampos;
import br.com.sicoob_credinova.arquivo_prejuizo_uad.model.UsuarioArquivo;
import br.com.sicoob_credinova.arquivo_prejuizo_uad.model.ValoresDosCampos;
import br.com.sicoob_credinova.arquivo_prejuizo_uad.utils.BibliotecaDeMetodos;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alisson Jaques
 */
public class CadastroDeDocumentos extends javax.swing.JInternalFrame {

    private final NomeDosCamposController controleNomeDosCampos;
    private final CaixaController controleCaixa;
    private final DocumentoController controleDocumento;
    private final ValoresDosCamposController controleValoresDosCampos;
    private List<NomeDosCampos> listaNomeDosCampos;
    private List<Documento> listaDocumentos;
    private UsuarioArquivo usuario;

    /**
     * Creates new form CadastroDeDocumentos
     *
     * @param usuario o usuário logado no sistema
     */
    public CadastroDeDocumentos(UsuarioArquivo usuario) {
        this.setFrameIcon(new ImageIcon("src\\br\\com\\sicoob_credinova\\arquivo_prejuizo_uad\\img\\arquivo.png"));
        initComponents();
        controleNomeDosCampos = new NomeDosCamposController();
        controleDocumento = new DocumentoController();
        controleCaixa = new CaixaController();
        controleValoresDosCampos = new ValoresDosCamposController();
        listaNomeDosCampos = controleNomeDosCampos.selecionar("");
        listaDocumentos = new ArrayList();
        this.usuario = usuario;
        preencherComboBox();
    }

    private void preencherComboBox() {
        getListaNomeDosCampos().forEach((nomeDosCampos) -> {
            getJcbTipoDocumental().addItem(nomeDosCampos.getNome());
        });
    }

    /**
     * O método limparTabela() limpa a tabela de interface do usuário
     */
    public void limparTabela() {
        DefaultTableModel dm = (DefaultTableModel) getJtTabela().getModel();
        dm.getDataVector().removeAllElements();
        dm.fireTableDataChanged();
    }

    private void preencherTabela(int caixa) {
        listaDocumentos = controleDocumento.selecionarPorCaixa(caixa);
        limparTabela();
        DefaultTableModel modelo = (DefaultTableModel) getJtTabela().getModel();
        getListaDocumentos().forEach((documento) -> {
            modelo.addRow(new Object[]{
                documento.getOrdem(),
                BibliotecaDeMetodos.getData(documento.getDateTime().toString()),
                controleNomeDosCampos.selecionarPorId(documento.getNomeDosCampos().getId_nome_dos_campos()),
                documento.getNomeUsuario(),
                documento.getStatus().toString()
            });
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpPrincipal = new javax.swing.JPanel();
        jlNumeroCaixa = new javax.swing.JLabel();
        jtfCaixa = new javax.swing.JTextField();
        jbPesquisarCaixa = new javax.swing.JButton();
        jlTipoDocumental = new javax.swing.JLabel();
        jcbTipoDocumental = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTabela = new javax.swing.JTable();
        jbAdicionar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jlNome1 = new javax.swing.JLabel();
        jtfValor1 = new javax.swing.JTextField();
        jlNome2 = new javax.swing.JLabel();
        jtfValor2 = new javax.swing.JTextField();
        jlNome3 = new javax.swing.JLabel();
        jtfValor3 = new javax.swing.JTextField();
        jlNome4 = new javax.swing.JLabel();
        jtfValor4 = new javax.swing.JTextField();
        jlNome5 = new javax.swing.JLabel();
        jtfValor5 = new javax.swing.JTextField();
        jlNome6 = new javax.swing.JLabel();
        jtfValor6 = new javax.swing.JTextField();
        jlNome7 = new javax.swing.JLabel();
        jtfValor7 = new javax.swing.JTextField();
        jlCaixa = new javax.swing.JLabel();
        jlInstrucao = new javax.swing.JLabel();

        setBackground(new java.awt.Color(72, 61, 139));
        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de Documentos");

        jlNumeroCaixa.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlNumeroCaixa.setText("Informe o número da caixa:");

        jtfCaixa.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jbPesquisarCaixa.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jbPesquisarCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sicoob_credinova/arquivo_prejuizo_uad/img/Search.png"))); // NOI18N
        jbPesquisarCaixa.setText("Pesquisar Caixa");
        jbPesquisarCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarCaixaActionPerformed(evt);
            }
        });

        jlTipoDocumental.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlTipoDocumental.setText("Escolha um tipo documental:");

        jcbTipoDocumental.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jcbTipoDocumental.setEnabled(false);
        jcbTipoDocumental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTipoDocumentalActionPerformed(evt);
            }
        });

        jtTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ordem", "Data Documento", "Descrição", "Usuário Última Alteração", "Situação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtTabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtTabela);
        if (jtTabela.getColumnModel().getColumnCount() > 0) {
            jtTabela.getColumnModel().getColumn(0).setPreferredWidth(10);
            jtTabela.getColumnModel().getColumn(4).setPreferredWidth(30);
        }

        jbAdicionar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jbAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sicoob_credinova/arquivo_prejuizo_uad/img/add_16.png"))); // NOI18N
        jbAdicionar.setText("Adicionar");
        jbAdicionar.setEnabled(false);
        jbAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdicionarActionPerformed(evt);
            }
        });

        jbEditar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jbEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sicoob_credinova/arquivo_prejuizo_uad/img/edit_16.png"))); // NOI18N
        jbEditar.setText("Editar");
        jbEditar.setEnabled(false);
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbExcluir.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sicoob_credinova/arquivo_prejuizo_uad/img/Cancel.png"))); // NOI18N
        jbExcluir.setText("Excluir");
        jbExcluir.setEnabled(false);
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbCancelar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sicoob_credinova/arquivo_prejuizo_uad/img/cancel_1.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.setEnabled(false);
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jlNome1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jlNome1.setText("Informação Complementar 1:");

        jtfValor1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        jlNome2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jlNome2.setText("Informação Complementar 2:");

        jtfValor2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        jlNome3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jlNome3.setText("Informação Complementar 3:");

        jtfValor3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        jlNome4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jlNome4.setText("Informação Complementar 4:");

        jtfValor4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        jlNome5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jlNome5.setText("Informação Complementar 5:");

        jtfValor5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        jlNome6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jlNome6.setText("Informação Complementar 6:");

        jtfValor6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        jlNome7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jlNome7.setText("Informação Complementar 7:");

        jtfValor7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlNome1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jtfValor7, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlNome7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtfValor6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlNome6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtfValor5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlNome2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtfValor3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlNome4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlNome5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfValor4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 911, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlNome3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jtfValor1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtfValor2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 911, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfValor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlNome2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfValor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlNome3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfValor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlNome4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfValor4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlNome5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfValor5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlNome6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfValor6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlNome7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfValor7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        jlCaixa.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jlInstrucao.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jlInstrucao.setText("Dê um duplo clique na tabela para edição ou remoção de um documento na caixa.");

        javax.swing.GroupLayout jpPrincipalLayout = new javax.swing.GroupLayout(jpPrincipal);
        jpPrincipal.setLayout(jpPrincipalLayout);
        jpPrincipalLayout.setHorizontalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpPrincipalLayout.createSequentialGroup()
                        .addComponent(jlNumeroCaixa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPesquisarCaixa)
                        .addGap(18, 18, 18)
                        .addComponent(jlTipoDocumental)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbTipoDocumental, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 957, Short.MAX_VALUE)
                    .addGroup(jpPrincipalLayout.createSequentialGroup()
                        .addComponent(jbAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(jbCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlInstrucao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1)))
                .addContainerGap())
        );
        jpPrincipalLayout.setVerticalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNumeroCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPesquisarCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlTipoDocumental)
                    .addComponent(jcbTipoDocumental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlInstrucao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbAdicionar)
                        .addComponent(jbEditar)
                        .addComponent(jbExcluir)
                        .addComponent(jbCancelar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean verificaCamposVazios() {
        return getJtfValor1().getText().equals("")
                && getJtfValor2().getText().equals("")
                && getJtfValor3().getText().equals("")
                && getJtfValor4().getText().equals("")
                && getJtfValor5().getText().equals("")
                && getJtfValor6().getText().equals("")
                && getJtfValor7().getText().equals("");
    }

    private void limparCampos() {
        getJtfValor1().setText("");
        getJtfValor2().setText("");
        getJtfValor3().setText("");
        getJtfValor4().setText("");
        getJtfValor5().setText("");
        getJtfValor6().setText("");
        getJtfValor7().setText("");
    }

    private void jcbTipoDocumentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTipoDocumentalActionPerformed
        NomeDosCampos nomeDosCampos = getListaNomeDosCampos().get(getJcbTipoDocumental().getSelectedIndex());
        getJlNome1().setText(nomeDosCampos.getNome1() + ":");
        getJlNome2().setText(nomeDosCampos.getNome2() + ":");
        getJlNome3().setText(nomeDosCampos.getNome3() + ":");
        getJlNome4().setText(nomeDosCampos.getNome4() + ":");
        getJlNome5().setText(nomeDosCampos.getNome5() + ":");
        getJlNome6().setText(nomeDosCampos.getNome6() + ":");
        getJlNome7().setText(nomeDosCampos.getNome7() + ":");
        limparCampos();
    }//GEN-LAST:event_jcbTipoDocumentalActionPerformed

    private void caixaEncontrada(boolean encontrou) {
        getJcbTipoDocumental().setEnabled(encontrou);
        getJbAdicionar().setEnabled(encontrou);
    }

    private void jbPesquisarCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarCaixaActionPerformed
        limparCampos();
        try {
            int id_caixa = Integer.parseInt(getJtfCaixa().getText());
            Caixa caixa = controleCaixa.selecionar(id_caixa);
            if (caixa != null) {
                getJlCaixa().setText("Rua: " + caixa.getRua() + " Avenida: " + caixa.getAvenida() + " Prédio: " + caixa.getPredio()
                        + " Andar: " + caixa.getAndar() + " Apto: " + caixa.getApartamento());
                caixaEncontrada(true);
                preencherTabela(id_caixa);
            } else {
                getJlCaixa().setText("Caixa não encontrada!");
                caixaEncontrada(false);
                limparTabela();
                JOptionPane.showMessageDialog(this, "A caixa informada não existe no sistema!", "Alerta", 2);
            }
        } catch (NumberFormatException e) {
            caixaEncontrada(false);
            JOptionPane.showMessageDialog(this, "Erro ao encontrar caixa! "
                    + "Identificador da caixa deve ser um número! " + e.getMessage(), "Alerta", 2);
        }
    }//GEN-LAST:event_jbPesquisarCaixaActionPerformed

    private void acaoAdicionar() {
        if (verificaCamposVazios()) {
            JOptionPane.showMessageDialog(this, "Preencha ao menos um campo para adicionar o documento", "Alerta", 2);
        } else {
            // gera os valores dos campos
            NomeDosCampos nomeDosCampos = new NomeDosCampos();
            nomeDosCampos.setId_nome_dos_campos(buscaIdNomeDosCampos(getJcbTipoDocumental().getSelectedIndex()));

            // gera o nome dos campos
            ValoresDosCampos valoresDosCampos = new ValoresDosCampos(0, getJtfValor1().getText(),
                    getJtfValor2().getText(), getJtfValor3().getText(), getJtfValor4().getText(),
                    getJtfValor5().getText(), getJtfValor6().getText(), getJtfValor7().getText());
            valoresDosCampos.setId_valores_dos_campos(getControleValoresDosCampos().inserir(valoresDosCampos));

            Caixa caixa = new Caixa();
            caixa.setId_caixa(Integer.parseInt(getJtfCaixa().getText()));
            Documento documento = new Documento(0, encontraOrdem(caixa.getId_caixa()), nomeDosCampos,
                    valoresDosCampos, caixa, getUsuario().getNomeDeUsuario(), Status.DISPONIVEL);
            getControleDocumento().inserir(documento);
            JOptionPane.showMessageDialog(this, "Documento cadastrado com sucesso!", "Alerta", 2);
            preencherTabela(caixa.getId_caixa());
        }
    }

    private int buscaIdNomeDosCampos(int indice) {
        return getListaNomeDosCampos().get(indice).getId_nome_dos_campos();
    }

    private int encontraOrdem(int id_caixa) {
        return getControleDocumento().getOrdem(id_caixa);
    }

    private void jbAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdicionarActionPerformed
        acaoAdicionar();
    }//GEN-LAST:event_jbAdicionarActionPerformed

    private void acionaCampos(boolean comando) {
        getJtfCaixa().setEnabled(comando);
        getJbPesquisarCaixa().setEnabled(comando);
        getJcbTipoDocumental().setEnabled(comando);
        getJbAdicionar().setEnabled(comando);
        getJbEditar().setEnabled(!comando);
        getJbExcluir().setEnabled(!comando);
        getJbCancelar().setEnabled(!comando);
        getJtTabela().setEnabled(comando);
    }

    private void preencheCamposDocumento(Documento documento) {
        getJtfValor1().setText(documento.getValoresDosCampos().getValor1());
        getJtfValor2().setText(documento.getValoresDosCampos().getValor2());
        getJtfValor3().setText(documento.getValoresDosCampos().getValor3());
        getJtfValor4().setText(documento.getValoresDosCampos().getValor4());
        getJtfValor5().setText(documento.getValoresDosCampos().getValor5());
        getJtfValor6().setText(documento.getValoresDosCampos().getValor6());
        getJtfValor7().setText(documento.getValoresDosCampos().getValor7());

        getJlNome1().setText(documento.getNomeDosCampos().getNome1() + ":");
        getJlNome2().setText(documento.getNomeDosCampos().getNome2() + ":");
        getJlNome3().setText(documento.getNomeDosCampos().getNome3() + ":");
        getJlNome4().setText(documento.getNomeDosCampos().getNome4() + ":");
        getJlNome5().setText(documento.getNomeDosCampos().getNome5() + ":");
        getJlNome6().setText(documento.getNomeDosCampos().getNome6() + ":");
        getJlNome7().setText(documento.getNomeDosCampos().getNome7() + ":");
    }

    private void jtTabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtTabelaMouseClicked
        if (evt.getClickCount() == 2) {
            int linha = getJtTabela().getSelectedRow();
            Documento documento = getControleDocumento().selecionar(getListaDocumentos().get(linha).getIdDocumento());
            preencheCamposDocumento(documento);
            acionaCampos(false);
        }
    }//GEN-LAST:event_jtTabelaMouseClicked

    private void atualizaComboBox() {
        int linha = getJtTabela().getSelectedRow();
        Documento documento = getControleDocumento().selecionar(getListaDocumentos().get(linha).getIdDocumento());
        int index = 0;
        for (NomeDosCampos nomeDosCampos : getListaNomeDosCampos()) {
            if (documento.getNomeDosCampos().getNome().equals(nomeDosCampos.getNome())) {
                getJcbTipoDocumental().setSelectedIndex(index);
            }
            index++;
        }
    }

    private void acaoCancelar() {
        acionaCampos(true);
        limparCampos();
        atualizaComboBox();
    }

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        acaoCancelar();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void acaoEditar() {
        if (verificaCamposVazios()) {
            JOptionPane.showMessageDialog(this, "Preencha ao menos um campo para adicionar o documento", "Alerta", 2);
        } else {
            int linha = getJtTabela().getSelectedRow();
            int id_caixa = Integer.parseInt(getJtfCaixa().getText());
            Documento documento = getControleDocumento().selecionar(getListaDocumentos().get(linha).getIdDocumento());
            
            ValoresDosCampos valores = documento.getValoresDosCampos();
            valores.setValor1(getJtfValor1().getText());
            valores.setValor2(getJtfValor2().getText());
            valores.setValor3(getJtfValor3().getText());
            valores.setValor4(getJtfValor4().getText());
            valores.setValor5(getJtfValor5().getText());
            valores.setValor6(getJtfValor6().getText());
            valores.setValor7(getJtfValor7().getText());
            
            getControleValoresDosCampos().editar(valores);
            documento.setDateTime(new java.sql.Date(new java.util.Date().getTime()));
            documento.setNomeUsuario(getUsuario().getNomeDeUsuario());
            getControleDocumento().editar(documento);
            
            limparCampos();
            preencherTabela(id_caixa);
            acionaCampos(true);
            JOptionPane.showMessageDialog(this, "Documento editado com sucesso!", "Alerta", 2);
        }

    }

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        acaoEditar();
    }//GEN-LAST:event_jbEditarActionPerformed

    private void acaoExcluir() {
        int op = JOptionPane.showConfirmDialog(this, "Deseja mesmo excluir o documento selecionado?", "Exclusão de Documento", JOptionPane.OK_CANCEL_OPTION);

        if (op == 0) {
            int linha = getJtTabela().getSelectedRow();
            int id_caixa = Integer.parseInt(getJtfCaixa().getText());
            Documento documento = getControleDocumento().selecionar(getListaDocumentos().get(linha).getIdDocumento());
            getControleDocumento().atualizaOrdens(documento.getIdDocumento(), id_caixa);
            getControleDocumento().excluir(documento.getIdDocumento());
            getControleValoresDosCampos().deletar(documento.getValoresDosCampos().getId_valores_dos_campos());
            limparCampos();
            preencherTabela(id_caixa);
            acionaCampos(true);
            JOptionPane.showMessageDialog(this, "Documento excluído com sucesso!", "Alerta", 2);
        }
    }

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        acaoExcluir();
    }//GEN-LAST:event_jbExcluirActionPerformed

    /**
     * @return the usuario
     */
    public UsuarioArquivo getUsuario() {
        return usuario;
    }

    /**
     * @param usuario the usuario to set
     */
    public void setUsuario(UsuarioArquivo usuario) {
        this.usuario = usuario;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbAdicionar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbPesquisarCaixa;
    private javax.swing.JComboBox<String> jcbTipoDocumental;
    private javax.swing.JLabel jlCaixa;
    private javax.swing.JLabel jlInstrucao;
    private javax.swing.JLabel jlNome1;
    private javax.swing.JLabel jlNome2;
    private javax.swing.JLabel jlNome3;
    private javax.swing.JLabel jlNome4;
    private javax.swing.JLabel jlNome5;
    private javax.swing.JLabel jlNome6;
    private javax.swing.JLabel jlNome7;
    private javax.swing.JLabel jlNumeroCaixa;
    private javax.swing.JLabel jlTipoDocumental;
    private javax.swing.JPanel jpPrincipal;
    private javax.swing.JTable jtTabela;
    private javax.swing.JTextField jtfCaixa;
    private javax.swing.JTextField jtfValor1;
    private javax.swing.JTextField jtfValor2;
    private javax.swing.JTextField jtfValor3;
    private javax.swing.JTextField jtfValor4;
    private javax.swing.JTextField jtfValor5;
    private javax.swing.JTextField jtfValor6;
    private javax.swing.JTextField jtfValor7;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the controleValoresDosCampos
     */
    public ValoresDosCamposController getControleValoresDosCampos() {
        return controleValoresDosCampos;
    }

    /**
     * @return the listaDocumentos
     */
    public List<Documento> getListaDocumentos() {
        return listaDocumentos;
    }

    /**
     * @param listaDocumentos the listaDocumentos to set
     */
    public void setListaDocumentos(List<Documento> listaDocumentos) {
        this.listaDocumentos = listaDocumentos;
    }

    /**
     * @return the controleDocumento
     */
    public DocumentoController getControleDocumento() {
        return controleDocumento;
    }

    /**
     * @return the controleCaixa
     */
    public CaixaController getControleCaixa() {
        return controleCaixa;
    }

    /**
     * @return the controleNomeDosCampos
     */
    public NomeDosCamposController getControleNomeDosCampos() {
        return controleNomeDosCampos;
    }

    /**
     * @return the listaNomeDosCampos
     */
    public List<NomeDosCampos> getListaNomeDosCampos() {
        return listaNomeDosCampos;
    }

    /**
     * @param listaNomeDosCampos the listaNomeDosCampos to set
     */
    public void setListaNomeDosCampos(List<NomeDosCampos> listaNomeDosCampos) {
        this.listaNomeDosCampos = listaNomeDosCampos;
    }

    /**
     * @return the jcbTipoDocumental
     */
    public javax.swing.JComboBox<String> getJcbTipoDocumental() {
        return jcbTipoDocumental;
    }

    /**
     * @param jcbTipoDocumental the jcbTipoDocumental to set
     */
    public void setJcbTipoDocumental(javax.swing.JComboBox<String> jcbTipoDocumental) {
        this.jcbTipoDocumental = jcbTipoDocumental;
    }

    /**
     * @return the jlNome1
     */
    public javax.swing.JLabel getJlNome1() {
        return jlNome1;
    }

    /**
     * @param jlNome1 the jlNome1 to set
     */
    public void setJlNome1(javax.swing.JLabel jlNome1) {
        this.jlNome1 = jlNome1;
    }

    /**
     * @return the jlNome2
     */
    public javax.swing.JLabel getJlNome2() {
        return jlNome2;
    }

    /**
     * @param jlNome2 the jlNome2 to set
     */
    public void setJlNome2(javax.swing.JLabel jlNome2) {
        this.jlNome2 = jlNome2;
    }

    /**
     * @return the jlNome3
     */
    public javax.swing.JLabel getJlNome3() {
        return jlNome3;
    }

    /**
     * @param jlNome3 the jlNome3 to set
     */
    public void setJlNome3(javax.swing.JLabel jlNome3) {
        this.jlNome3 = jlNome3;
    }

    /**
     * @return the jlNome4
     */
    public javax.swing.JLabel getJlNome4() {
        return jlNome4;
    }

    /**
     * @param jlNome4 the jlNome4 to set
     */
    public void setJlNome4(javax.swing.JLabel jlNome4) {
        this.jlNome4 = jlNome4;
    }

    /**
     * @return the jlNome5
     */
    public javax.swing.JLabel getJlNome5() {
        return jlNome5;
    }

    /**
     * @param jlNome5 the jlNome5 to set
     */
    public void setJlNome5(javax.swing.JLabel jlNome5) {
        this.jlNome5 = jlNome5;
    }

    /**
     * @return the jlNome6
     */
    public javax.swing.JLabel getJlNome6() {
        return jlNome6;
    }

    /**
     * @param jlNome6 the jlNome6 to set
     */
    public void setJlNome6(javax.swing.JLabel jlNome6) {
        this.jlNome6 = jlNome6;
    }

    /**
     * @return the jlNome7
     */
    public javax.swing.JLabel getJlNome7() {
        return jlNome7;
    }

    /**
     * @param jlNome7 the jlNome7 to set
     */
    public void setJlNome7(javax.swing.JLabel jlNome7) {
        this.jlNome7 = jlNome7;
    }

    /**
     * @return the jlNumeroCaixa
     */
    public javax.swing.JLabel getJlNumeroCaixa() {
        return jlNumeroCaixa;
    }

    /**
     * @param jlNumeroCaixa the jlNumeroCaixa to set
     */
    public void setJlNumeroCaixa(javax.swing.JLabel jlNumeroCaixa) {
        this.jlNumeroCaixa = jlNumeroCaixa;
    }

    /**
     * @return the jlTipoDocumental
     */
    public javax.swing.JLabel getJlTipoDocumental() {
        return jlTipoDocumental;
    }

    /**
     * @param jlTipoDocumental the jlTipoDocumental to set
     */
    public void setJlTipoDocumental(javax.swing.JLabel jlTipoDocumental) {
        this.jlTipoDocumental = jlTipoDocumental;
    }

    /**
     * @return the jpPrincipal
     */
    public javax.swing.JPanel getJpPrincipal() {
        return jpPrincipal;
    }

    /**
     * @param jpPrincipal the jpPrincipal to set
     */
    public void setJpPrincipal(javax.swing.JPanel jpPrincipal) {
        this.jpPrincipal = jpPrincipal;
    }

    /**
     * @return the jtfCaixa
     */
    public javax.swing.JTextField getJtfCaixa() {
        return jtfCaixa;
    }

    /**
     * @param jtfCaixa the jtfCaixa to set
     */
    public void setJtfCaixa(javax.swing.JTextField jtfCaixa) {
        this.jtfCaixa = jtfCaixa;
    }

    /**
     * @return the jtfValor1
     */
    public javax.swing.JTextField getJtfValor1() {
        return jtfValor1;
    }

    /**
     * @param jtfValor1 the jtfValor1 to set
     */
    public void setJtfValor1(javax.swing.JTextField jtfValor1) {
        this.jtfValor1 = jtfValor1;
    }

    /**
     * @return the jtfValor2
     */
    public javax.swing.JTextField getJtfValor2() {
        return jtfValor2;
    }

    /**
     * @param jtfValor2 the jtfValor2 to set
     */
    public void setJtfValor2(javax.swing.JTextField jtfValor2) {
        this.jtfValor2 = jtfValor2;
    }

    /**
     * @return the jtfValor3
     */
    public javax.swing.JTextField getJtfValor3() {
        return jtfValor3;
    }

    /**
     * @param jtfValor3 the jtfValor3 to set
     */
    public void setJtfValor3(javax.swing.JTextField jtfValor3) {
        this.jtfValor3 = jtfValor3;
    }

    /**
     * @return the jtfValor4
     */
    public javax.swing.JTextField getJtfValor4() {
        return jtfValor4;
    }

    /**
     * @param jtfValor4 the jtfValor4 to set
     */
    public void setJtfValor4(javax.swing.JTextField jtfValor4) {
        this.jtfValor4 = jtfValor4;
    }

    /**
     * @return the jtfValor5
     */
    public javax.swing.JTextField getJtfValor5() {
        return jtfValor5;
    }

    /**
     * @param jtfValor5 the jtfValor5 to set
     */
    public void setJtfValor5(javax.swing.JTextField jtfValor5) {
        this.jtfValor5 = jtfValor5;
    }

    /**
     * @return the jtfValor6
     */
    public javax.swing.JTextField getJtfValor6() {
        return jtfValor6;
    }

    /**
     * @param jtfValor6 the jtfValor6 to set
     */
    public void setJtfValor6(javax.swing.JTextField jtfValor6) {
        this.jtfValor6 = jtfValor6;
    }

    /**
     * @return the jtfValor7
     */
    public javax.swing.JTextField getJtfValor7() {
        return jtfValor7;
    }

    /**
     * @param jtfValor7 the jtfValor7 to set
     */
    public void setJtfValor7(javax.swing.JTextField jtfValor7) {
        this.jtfValor7 = jtfValor7;
    }

    /**
     * @return the jlCaixa
     */
    public javax.swing.JLabel getJlCaixa() {
        return jlCaixa;
    }

    /**
     * @param jlCaixa the jlCaixa to set
     */
    public void setJlCaixa(javax.swing.JLabel jlCaixa) {
        this.jlCaixa = jlCaixa;
    }

    /**
     * @return the jbAdicionar
     */
    public javax.swing.JButton getJbAdicionar() {
        return jbAdicionar;
    }

    /**
     * @param jbAdicionar the jbAdicionar to set
     */
    public void setJbAdicionar(javax.swing.JButton jbAdicionar) {
        this.jbAdicionar = jbAdicionar;
    }

    /**
     * @return the jbCancelar
     */
    public javax.swing.JButton getJbCancelar() {
        return jbCancelar;
    }

    /**
     * @param jbCancelar the jbCancelar to set
     */
    public void setJbCancelar(javax.swing.JButton jbCancelar) {
        this.jbCancelar = jbCancelar;
    }

    /**
     * @return the jbEditar
     */
    public javax.swing.JButton getJbEditar() {
        return jbEditar;
    }

    /**
     * @param jbEditar the jbEditar to set
     */
    public void setJbEditar(javax.swing.JButton jbEditar) {
        this.jbEditar = jbEditar;
    }

    /**
     * @return the jbExcluir
     */
    public javax.swing.JButton getJbExcluir() {
        return jbExcluir;
    }

    /**
     * @param jbExcluir the jbExcluir to set
     */
    public void setJbExcluir(javax.swing.JButton jbExcluir) {
        this.jbExcluir = jbExcluir;
    }

    /**
     * @return the jtTabela
     */
    public javax.swing.JTable getJtTabela() {
        return jtTabela;
    }

    /**
     * @param jtTabela the jtTabela to set
     */
    public void setJtTabela(javax.swing.JTable jtTabela) {
        this.jtTabela = jtTabela;
    }

    /**
     * @return the jbPesquisarCaixa
     */
    public javax.swing.JButton getJbPesquisarCaixa() {
        return jbPesquisarCaixa;
    }
}
