package br.com.aj_sistemas.novo_sgad.view.usuarios;

import br.com.aj_sistemas.novo_sgad.controller.UsuarioController;
import br.com.aj_sistemas.novo_sgad.model.UsuarioArquivo;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alisson Jaques
 */
public class AdministrarUsuarios extends javax.swing.JInternalFrame {

    private ArrayList<UsuarioArquivo> usuarios;
    UsuarioController controle;
    
    /**
     * Creates new form AdministrarUsuarios
     */
    public AdministrarUsuarios() {
        this.setFrameIcon(new ImageIcon("src\\br\\com\\aj_sistemas\\novo_sgad\\img\\arquivo.png"));
        initComponents();
        controle = new UsuarioController();
        usuarios = controle.selecionarTodos();
        preencherTabela();
    }

    private void acaoNovoUsuario() {
        CadastrarNovoUsuario telaCadastroNovoUsuario = new CadastrarNovoUsuario(this);
        telaCadastroNovoUsuario.setVisible(true);
    }

    private void preencherTabela() {
        usuarios = controle.selecionarTodos();
        limparTabela();
        DefaultTableModel modelo = (DefaultTableModel) getJtTabela().getModel();
        getUsuarios().forEach((usuario) -> {
            modelo.addRow(new Object[]{
                usuario.getNome(),
                usuario.getNomeDeUsuario(),
                usuario.getCpf(),
                usuario.getPerfil().toString()
            });
        });
    }
    
    public void popularTabela() {
        limparTabela();
        DefaultTableModel modelo = (DefaultTableModel) getJtTabela().getModel();
        getUsuarios().forEach((usuario) -> {
            modelo.addRow(new Object[]{
                usuario.getNome(),
                usuario.getNomeDeUsuario(),
                usuario.getCpf(),
                usuario.getPerfil().toString()
            });
        });
    }
     
    /**
     * O método limparTabela() limpa a tabela de interface do usuário
     */
    public void limparTabela() {
        DefaultTableModel dm = (DefaultTableModel) getJtTabela().getModel();
        dm.getDataVector().removeAllElements();
        dm.fireTableDataChanged();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpPrincipal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTabela = new javax.swing.JTable();
        jbAlterar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jbNovoUsuario = new javax.swing.JButton();

        setBackground(new java.awt.Color(72, 61, 139));
        setClosable(true);
        setIconifiable(true);
        setTitle("Administração de Usuários");

        jtTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Nome de Login", "CPF", "Perfil"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtTabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtTabela);

        jbAlterar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/aj_sistemas/novo_sgad/img/edit_16.png"))); // NOI18N
        jbAlterar.setText("Alterar");
        jbAlterar.setEnabled(false);
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });
        jbAlterar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbAlterarKeyPressed(evt);
            }
        });

        jbExcluir.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/aj_sistemas/novo_sgad/img/Cancel.png"))); // NOI18N
        jbExcluir.setText("Excluir");
        jbExcluir.setEnabled(false);
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });
        jbExcluir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbExcluirKeyPressed(evt);
            }
        });

        jbCancelar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/aj_sistemas/novo_sgad/img/cancel_1.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.setEnabled(false);
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });
        jbCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbCancelarKeyPressed(evt);
            }
        });

        jbNovoUsuario.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jbNovoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/aj_sistemas/novo_sgad/img/add_16.png"))); // NOI18N
        jbNovoUsuario.setText("Novo Usuário");
        jbNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoUsuarioActionPerformed(evt);
            }
        });
        jbNovoUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbNovoUsuarioKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jpPrincipalLayout = new javax.swing.GroupLayout(jpPrincipal);
        jpPrincipal.setLayout(jpPrincipalLayout);
        jpPrincipalLayout.setHorizontalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                    .addGroup(jpPrincipalLayout.createSequentialGroup()
                        .addComponent(jbAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbNovoUsuario)))
                .addContainerGap())
        );
        jpPrincipalLayout.setVerticalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAlterar)
                    .addComponent(jbExcluir)
                    .addComponent(jbCancelar)
                    .addComponent(jbNovoUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoUsuarioActionPerformed
        acaoNovoUsuario();
    }//GEN-LAST:event_jbNovoUsuarioActionPerformed

    private void jbNovoUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbNovoUsuarioKeyPressed
        acaoNovoUsuario();
    }//GEN-LAST:event_jbNovoUsuarioKeyPressed
    
    private void acionaTodosCampos(){
        getJbNovoUsuario().setEnabled(true);
        getJtTabela().setEnabled(true);
        getJbAlterar().setEnabled(false);
        getJbExcluir().setEnabled(false);
        getJbCancelar().setEnabled(false);                
    }
    
    private void desAcionaTodosCampos(){
        getJbNovoUsuario().setEnabled(false);
        getJtTabela().setEnabled(false);
        getJbAlterar().setEnabled(true);
        getJbExcluir().setEnabled(true);
        getJbCancelar().setEnabled(true);                
    }
    
    private void jtTabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtTabelaMouseClicked
        if (evt.getClickCount() == 2) {
            desAcionaTodosCampos();
        }
    }//GEN-LAST:event_jtTabelaMouseClicked
    
    private void acaoCancelar(){
        acionaTodosCampos();
    }
    
    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        acaoCancelar();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbCancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbCancelarKeyPressed
        acaoCancelar();
    }//GEN-LAST:event_jbCancelarKeyPressed
    
    private void acaoExcluir(){        
        int op = JOptionPane.showConfirmDialog(this, "Deseja mesmo excluir o usuário selecionado?", "Excluir", JOptionPane.OK_CANCEL_OPTION);

        if (op == 0) {
            int linhaSelecionada = getJtTabela().getSelectedRow();
            controle.deletar(getJtTabela().getValueAt(linhaSelecionada, 2).toString());
            preencherTabela();
            acionaTodosCampos();
        }
    }
    
    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        acaoExcluir();
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbExcluirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbExcluirKeyPressed
        acaoExcluir();
    }//GEN-LAST:event_jbExcluirKeyPressed
    
    private void acaoAlterar(){
        usuarios = controle.selecionarTodos();
        UsuarioArquivo usuario = getUsuarios().get(getJtTabela().getSelectedRow());
        preencherTabela();
        EditarNovoUsuario telaEdicao = new EditarNovoUsuario(usuario);
        telaEdicao.setVisible(true);
        acionaTodosCampos();
    }
    
    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        acaoAlterar();
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jbAlterarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbAlterarKeyPressed
        acaoAlterar();
    }//GEN-LAST:event_jbAlterarKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbNovoUsuario;
    private javax.swing.JPanel jpPrincipal;
    private javax.swing.JTable jtTabela;
    // End of variables declaration//GEN-END:variables
    /**
     * @return the usuarios
     */
    public ArrayList<UsuarioArquivo> getUsuarios() {
        return usuarios;
    }

    /**
     * @param usuarios the usuarios to set
     */
    public void setUsuarios(ArrayList<UsuarioArquivo> usuarios) {
        this.usuarios = usuarios;
    }
    
    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @param jScrollPane1 the jScrollPane1 to set
     */
    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    /**
     * @return the jbAlterar
     */
    public javax.swing.JButton getJbAlterar() {
        return jbAlterar;
    }

    /**
     * @param jbAlterar the jbAlterar to set
     */
    public void setJbAlterar(javax.swing.JButton jbAlterar) {
        this.jbAlterar = jbAlterar;
    }

    /**
     * @return the jbCancelar
     */
    public javax.swing.JButton getJbCancelar() {
        return jbCancelar;
    }

    /**
     * @param jbCancelar the jbCancelar to set
     */
    public void setJbCancelar(javax.swing.JButton jbCancelar) {
        this.jbCancelar = jbCancelar;
    }

    /**
     * @return the jbExcluir
     */
    public javax.swing.JButton getJbExcluir() {
        return jbExcluir;
    }

    /**
     * @param jbExcluir the jbExcluir to set
     */
    public void setJbExcluir(javax.swing.JButton jbExcluir) {
        this.jbExcluir = jbExcluir;
    }

    /**
     * @return the jbNovoUsuario
     */
    public javax.swing.JButton getJbNovoUsuario() {
        return jbNovoUsuario;
    }

    /**
     * @param jbNovoUsuario the jbNovoUsuario to set
     */
    public void setJbNovoUsuario(javax.swing.JButton jbNovoUsuario) {
        this.jbNovoUsuario = jbNovoUsuario;
    }
   
    /**
     * @return the jpPrincipal
     */
    public javax.swing.JPanel getJpPrincipal() {
        return jpPrincipal;
    }

    /**
     * @param jpPrincipal the jpPrincipal to set
     */
    public void setJpPrincipal(javax.swing.JPanel jpPrincipal) {
        this.jpPrincipal = jpPrincipal;
    }

    /**
     * @return the jtTabela
     */
    public javax.swing.JTable getJtTabela() {
        return jtTabela;
    }

    /**
     * @param jtTabela the jtTabela to set
     */
    public void setJtTabela(javax.swing.JTable jtTabela) {
        this.jtTabela = jtTabela;
    }

}
