package br.com.sicoob_credinova.arquivo_prejuizo_uad.view.principal;

import br.com.sicoob_credinova.arquivo_prejuizo_uad.model.UsuarioArquivo;
import br.com.sicoob_credinova.arquivo_prejuizo_uad.view.consultas.ConsultaDeDocumentos;
import br.com.sicoob_credinova.arquivo_prejuizo_uad.view.documentos.CadastroDeDocumentos;
import br.com.sicoob_credinova.arquivo_prejuizo_uad.view.tipo_documental.CadastroTipoDocumental;
import br.com.sicoob_credinova.arquivo_prejuizo_uad.view.tipo_documental.ConsultaTipoDocumental;
import br.com.sicoob_credinova.arquivo_prejuizo_uad.view.tipo_documental.EdicaoExclusaoTipoDocumental;
import br.com.sicoob_credinova.arquivo_prejuizo_uad.view.login.TelaDeLogin;
import br.com.sicoob_credinova.arquivo_prejuizo_uad.view.relatorios.EtiquetaCaixa;
import br.com.sicoob_credinova.arquivo_prejuizo_uad.view.usuarios.AdministrarUsuarios;
import br.com.sicoob_credinova.arquivo_prejuizo_uad.view.usuarios.AlterarSenha;
import java.awt.Toolkit;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Alisson Jaques
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private UsuarioArquivo usuarioLogado;
    private TelaDeLogin telaLogin;
    private AdministrarUsuarios administrarUsuarios;
    private AlterarSenha alterarSenha;
    private CadastroTipoDocumental cadastroTipoDocumental;
    private ConsultaTipoDocumental consultaTipoDocumental;
    private EdicaoExclusaoTipoDocumental edicaoExclusaoTipoDocumental;
    private CadastroDeDocumentos cadastroDeDocumentos;
    private ConsultaDeDocumentos consultaDeDocumentos;
    private EtiquetaCaixa etiquetaCaixa;

    /**
     * Creates new form TelaPrincipal
     *
     * @throws java.lang.ClassNotFoundException
     * @throws java.lang.InstantiationException
     * @throws java.lang.IllegalAccessException
     * @throws javax.swing.UnsupportedLookAndFeelException
     */
    public TelaPrincipal() throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("src\\br\\com\\sicoob_credinova\\arquivo_prejuizo_uad\\img\\faviconP.png"));
        initComponents();
        usuarioLogado = new UsuarioArquivo();
        centralizarLogo(jlLogo);
        String lookAndFeelClassName = UIManager.getSystemLookAndFeelClassName();
        UIManager.setLookAndFeel(lookAndFeelClassName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpPrincipal = new javax.swing.JDesktopPane();
        jlLogo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jmbMenus = new javax.swing.JMenuBar();
        jmLogin = new javax.swing.JMenu();
        jmiLogin = new javax.swing.JMenuItem();
        jmiSair = new javax.swing.JMenuItem();
        jmCadastrarDocumentos = new javax.swing.JMenu();
        jmiCadastrarDocumentos = new javax.swing.JMenuItem();
        jmConsultas = new javax.swing.JMenu();
        jmiConsultaDocumentos = new javax.swing.JMenuItem();
        jmRelatorios = new javax.swing.JMenu();
        jmiEtiquetas = new javax.swing.JMenuItem();
        jmConfiguracao = new javax.swing.JMenu();
        jmiAlterarSenha = new javax.swing.JMenuItem();
        jmiAdministrarUsuários = new javax.swing.JMenuItem();
        jmAdministrarTipoDocumental = new javax.swing.JMenu();
        jmiCadastrarTipoDocumental = new javax.swing.JMenuItem();
        jmiConsultaTipoDocumental = new javax.swing.JMenuItem();
        jmiEditarExcluir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Arquivo Prejuízo 1.0.0");
        setBackground(new java.awt.Color(0, 128, 128));

        jdpPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        jdpPrincipal.setPreferredSize(new java.awt.Dimension(856, 751));

        jlLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sicoob_credinova/arquivo_prejuizo_uad/img/credinova.jpg"))); // NOI18N
        jlLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jdpPrincipal.add(jlLogo);
        jlLogo.setBounds(0, 0, 1640, 980);

        jScrollPane1.setViewportView(jTree1);

        jmbMenus.setBackground(new java.awt.Color(72, 61, 139));

        jmLogin.setForeground(new java.awt.Color(255, 255, 255));
        jmLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sicoob_credinova/arquivo_prejuizo_uad/img/loginPasta32.png"))); // NOI18N
        jmLogin.setText("Login");
        jmLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jmiLogin.setBackground(new java.awt.Color(204, 204, 204));
        jmiLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jmiLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sicoob_credinova/arquivo_prejuizo_uad/img/PessoaFisica.png"))); // NOI18N
        jmiLogin.setText("Logar");
        jmiLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLoginActionPerformed(evt);
            }
        });
        jmLogin.add(jmiLogin);

        jmiSair.setBackground(new java.awt.Color(204, 204, 204));
        jmiSair.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jmiSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sicoob_credinova/arquivo_prejuizo_uad/img/Sair32.png"))); // NOI18N
        jmiSair.setText("Sair");
        jmiSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSairActionPerformed(evt);
            }
        });
        jmLogin.add(jmiSair);

        jmbMenus.add(jmLogin);

        jmCadastrarDocumentos.setBackground(new java.awt.Color(51, 51, 51));
        jmCadastrarDocumentos.setForeground(new java.awt.Color(255, 255, 255));
        jmCadastrarDocumentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sicoob_credinova/arquivo_prejuizo_uad/img/arquivo.png"))); // NOI18N
        jmCadastrarDocumentos.setText("Cadastrar Documentos");
        jmCadastrarDocumentos.setEnabled(false);
        jmCadastrarDocumentos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jmiCadastrarDocumentos.setBackground(new java.awt.Color(204, 204, 204));
        jmiCadastrarDocumentos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jmiCadastrarDocumentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sicoob_credinova/arquivo_prejuizo_uad/img/documento32.png"))); // NOI18N
        jmiCadastrarDocumentos.setText("Cadastrar");
        jmiCadastrarDocumentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastrarDocumentosActionPerformed(evt);
            }
        });
        jmCadastrarDocumentos.add(jmiCadastrarDocumentos);

        jmbMenus.add(jmCadastrarDocumentos);

        jmConsultas.setBackground(new java.awt.Color(51, 51, 51));
        jmConsultas.setForeground(new java.awt.Color(255, 255, 255));
        jmConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sicoob_credinova/arquivo_prejuizo_uad/img/consultaDocumento32.png"))); // NOI18N
        jmConsultas.setText("Consultas");
        jmConsultas.setEnabled(false);
        jmConsultas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jmiConsultaDocumentos.setBackground(new java.awt.Color(204, 204, 204));
        jmiConsultaDocumentos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jmiConsultaDocumentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sicoob_credinova/arquivo_prejuizo_uad/img/srch_32.png"))); // NOI18N
        jmiConsultaDocumentos.setText("Documentos Cadastrados");
        jmiConsultaDocumentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsultaDocumentosActionPerformed(evt);
            }
        });
        jmConsultas.add(jmiConsultaDocumentos);

        jmbMenus.add(jmConsultas);

        jmRelatorios.setForeground(new java.awt.Color(255, 255, 255));
        jmRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sicoob_credinova/arquivo_prejuizo_uad/img/imgEnquete.png"))); // NOI18N
        jmRelatorios.setText("Relatórios");
        jmRelatorios.setEnabled(false);
        jmRelatorios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jmiEtiquetas.setBackground(new java.awt.Color(204, 204, 204));
        jmiEtiquetas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jmiEtiquetas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sicoob_credinova/arquivo_prejuizo_uad/img/report_32.png"))); // NOI18N
        jmiEtiquetas.setText("Gerar Etiquetas");
        jmiEtiquetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEtiquetasActionPerformed(evt);
            }
        });
        jmRelatorios.add(jmiEtiquetas);

        jmbMenus.add(jmRelatorios);

        jmConfiguracao.setForeground(new java.awt.Color(255, 255, 255));
        jmConfiguracao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sicoob_credinova/arquivo_prejuizo_uad/img/apps_32.png"))); // NOI18N
        jmConfiguracao.setText("Sistema");
        jmConfiguracao.setEnabled(false);
        jmConfiguracao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jmiAlterarSenha.setBackground(new java.awt.Color(204, 204, 204));
        jmiAlterarSenha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jmiAlterarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sicoob_credinova/arquivo_prejuizo_uad/img/password32.png"))); // NOI18N
        jmiAlterarSenha.setText("Alterar Senha");
        jmiAlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAlterarSenhaActionPerformed(evt);
            }
        });
        jmConfiguracao.add(jmiAlterarSenha);

        jmiAdministrarUsuários.setBackground(new java.awt.Color(204, 204, 204));
        jmiAdministrarUsuários.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jmiAdministrarUsuários.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sicoob_credinova/arquivo_prejuizo_uad/img/relacionamento.png"))); // NOI18N
        jmiAdministrarUsuários.setText("Administrar Usuários");
        jmiAdministrarUsuários.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAdministrarUsuáriosActionPerformed(evt);
            }
        });
        jmConfiguracao.add(jmiAdministrarUsuários);

        jmAdministrarTipoDocumental.setBackground(new java.awt.Color(204, 204, 204));
        jmAdministrarTipoDocumental.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sicoob_credinova/arquivo_prejuizo_uad/img/Product-documentation (3).png"))); // NOI18N
        jmAdministrarTipoDocumental.setText("Administrar Tipos Documentais");
        jmAdministrarTipoDocumental.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jmiCadastrarTipoDocumental.setBackground(new java.awt.Color(204, 204, 204));
        jmiCadastrarTipoDocumental.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmiCadastrarTipoDocumental.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sicoob_credinova/arquivo_prejuizo_uad/img/documento32.png"))); // NOI18N
        jmiCadastrarTipoDocumental.setText("Cadastrar");
        jmiCadastrarTipoDocumental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastrarTipoDocumentalActionPerformed(evt);
            }
        });
        jmAdministrarTipoDocumental.add(jmiCadastrarTipoDocumental);

        jmiConsultaTipoDocumental.setBackground(new java.awt.Color(204, 204, 204));
        jmiConsultaTipoDocumental.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmiConsultaTipoDocumental.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sicoob_credinova/arquivo_prejuizo_uad/img/srch_32.png"))); // NOI18N
        jmiConsultaTipoDocumental.setText("Consultar");
        jmiConsultaTipoDocumental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsultaTipoDocumentalActionPerformed(evt);
            }
        });
        jmAdministrarTipoDocumental.add(jmiConsultaTipoDocumental);

        jmiEditarExcluir.setBackground(new java.awt.Color(204, 204, 204));
        jmiEditarExcluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmiEditarExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sicoob_credinova/arquivo_prejuizo_uad/img/accessories-text-editor (3).png"))); // NOI18N
        jmiEditarExcluir.setText("Editar / Excluir");
        jmiEditarExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEditarExcluirActionPerformed(evt);
            }
        });
        jmAdministrarTipoDocumental.add(jmiEditarExcluir);

        jmConfiguracao.add(jmAdministrarTipoDocumental);

        jmbMenus.add(jmConfiguracao);

        setJMenuBar(jmbMenus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1646, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * O método centralizarJInternalFrame(JInternalFrame) centraliza o frame
     * passado como argumento na tela da aplicação.
     *
     * @param frame uma intância da classe JInternalFrame a ser centralizada na
     * aplicação.
     */
    private void centralizarJInternalFrame(JInternalFrame frame) {

        int lDesk = getJdpPrincipal().getWidth();
        int aDesk = getJdpPrincipal().getHeight();

        int lFrame = frame.getWidth();
        int aFrame = frame.getHeight();

        frame.setLocation(lDesk / 2 - lFrame / 2, aDesk / 2 - aFrame / 2);
    }

    private void centralizarLogo(JLabel logo) {
        int lDesk = getJdpPrincipal().getWidth();
        int aDesk = getJdpPrincipal().getHeight();

        int lLogo = logo.getWidth();
        int aLogo = logo.getHeight();
        logo.setLocation(lDesk / 2 - lLogo / 2, aDesk / 2 - aLogo / 2);
    }


    private void jmiSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSairActionPerformed
        int op = JOptionPane.showConfirmDialog(this, "Deseja mesmo sair do sistema?", "Encerrar Aplicação", JOptionPane.OK_CANCEL_OPTION);

        if (op == 0) {
            dispose();
        }
    }//GEN-LAST:event_jmiSairActionPerformed

    private void jmiLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLoginActionPerformed
        centralizarLogo(getJlLogo());
        TelaDeLogin tl = new TelaDeLogin(this, true, getUsuarioLogado());
        tl.setVisible(true);
    }//GEN-LAST:event_jmiLoginActionPerformed

    private void jmiAdministrarUsuáriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAdministrarUsuáriosActionPerformed
        centralizarLogo(getJlLogo());
        if (getAdministrarUsuarios() == null) {
            setAdministrarUsuarios(new AdministrarUsuarios());
            getJdpPrincipal().add(getAdministrarUsuarios());
            getAdministrarUsuarios().setVisible(true);
            centralizarJInternalFrame(getAdministrarUsuarios());
        } else if (getAdministrarUsuarios() != null) {
            if (getAdministrarUsuarios().isClosed()) {
                setAdministrarUsuarios(new AdministrarUsuarios());
                getJdpPrincipal().add(getAdministrarUsuarios());
                getAdministrarUsuarios().setVisible(true);
                centralizarJInternalFrame(getAdministrarUsuarios());
            }
        }
    }//GEN-LAST:event_jmiAdministrarUsuáriosActionPerformed

    private void jmiAlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAlterarSenhaActionPerformed
        centralizarLogo(getJlLogo());
        if (getAlterarSenha() == null) {
            setAlterarSenha(new AlterarSenha(getUsuarioLogado()));
            getJdpPrincipal().add(getAlterarSenha());
            getAlterarSenha().setVisible(true);
            centralizarJInternalFrame(getAlterarSenha());
        } else if (getAlterarSenha() != null) {
            if (getAlterarSenha().isClosed()) {
                setAlterarSenha(new AlterarSenha(getUsuarioLogado()));
                getJdpPrincipal().add(getAlterarSenha());
                getAlterarSenha().setVisible(true);
                centralizarJInternalFrame(getAlterarSenha());
            }
        }
    }//GEN-LAST:event_jmiAlterarSenhaActionPerformed

    private void jmiCadastrarTipoDocumentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastrarTipoDocumentalActionPerformed
        centralizarLogo(getJlLogo());
        if (getCadastroTipoDocumental() == null) {
            setCadastroTipoDocumental(new CadastroTipoDocumental());
            getJdpPrincipal().add(getCadastroTipoDocumental());
            getCadastroTipoDocumental().setVisible(true);
            centralizarJInternalFrame(getCadastroTipoDocumental());
        } else if (getCadastroTipoDocumental() != null) {
            if (getCadastroTipoDocumental().isClosed()) {
                setCadastroTipoDocumental(new CadastroTipoDocumental());
                getJdpPrincipal().add(getCadastroTipoDocumental());
                getCadastroTipoDocumental().setVisible(true);
                centralizarJInternalFrame(getCadastroTipoDocumental());
            }
        }
    }//GEN-LAST:event_jmiCadastrarTipoDocumentalActionPerformed

    private void jmiConsultaTipoDocumentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsultaTipoDocumentalActionPerformed
        centralizarLogo(getJlLogo());
        if (getConsultaTipoDocumental() == null) {
            setConsultaTipoDocumental(new ConsultaTipoDocumental());
            getJdpPrincipal().add(getConsultaTipoDocumental());
            getConsultaTipoDocumental().setVisible(true);
            centralizarJInternalFrame(getConsultaTipoDocumental());
        } else if (getConsultaTipoDocumental() != null) {
            if (getConsultaTipoDocumental().isClosed()) {
                setConsultaTipoDocumental(new ConsultaTipoDocumental());
                getJdpPrincipal().add(getConsultaTipoDocumental());
                getConsultaTipoDocumental().setVisible(true);
                centralizarJInternalFrame(getConsultaTipoDocumental());
            }
        }
    }//GEN-LAST:event_jmiConsultaTipoDocumentalActionPerformed

    private void jmiEditarExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEditarExcluirActionPerformed
        centralizarLogo(getJlLogo());
        if (getEdicaoExclusaoTipoDocumental() == null) {
            setEdicaoExclusaoTipoDocumental(new EdicaoExclusaoTipoDocumental());
            getJdpPrincipal().add(getEdicaoExclusaoTipoDocumental());
            getEdicaoExclusaoTipoDocumental().setVisible(true);
            centralizarJInternalFrame(getEdicaoExclusaoTipoDocumental());
        } else if (getEdicaoExclusaoTipoDocumental() != null) {
            if (getEdicaoExclusaoTipoDocumental().isClosed()) {
                setEdicaoExclusaoTipoDocumental(new EdicaoExclusaoTipoDocumental());
                getJdpPrincipal().add(getEdicaoExclusaoTipoDocumental());
                getEdicaoExclusaoTipoDocumental().setVisible(true);
                centralizarJInternalFrame(getEdicaoExclusaoTipoDocumental());
            }
        }
    }//GEN-LAST:event_jmiEditarExcluirActionPerformed

    private void jmiCadastrarDocumentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastrarDocumentosActionPerformed
        centralizarLogo(getJlLogo());
        if (getCadastroDeDocumentos() == null) {
            setCadastroDeDocumentos(new CadastroDeDocumentos(getUsuarioLogado()));
            getJdpPrincipal().add(getCadastroDeDocumentos());
            getCadastroDeDocumentos().setVisible(true);
            centralizarJInternalFrame(getCadastroDeDocumentos());
        } else if (getCadastroDeDocumentos() != null) {
            if (getCadastroDeDocumentos().isClosed()) {
                setCadastroDeDocumentos(new CadastroDeDocumentos(getUsuarioLogado()));
                getJdpPrincipal().add(getCadastroDeDocumentos());
                getCadastroDeDocumentos().setVisible(true);
                centralizarJInternalFrame(getCadastroDeDocumentos());
            }
        }
    }//GEN-LAST:event_jmiCadastrarDocumentosActionPerformed

    private void jmiConsultaDocumentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsultaDocumentosActionPerformed
        centralizarLogo(getJlLogo());
        if (getConsultaDeDocumentos() == null) {
            setConsultaDeDocumentos(new ConsultaDeDocumentos());
            getJdpPrincipal().add(getConsultaDeDocumentos());
            getConsultaDeDocumentos().setVisible(true);
            centralizarJInternalFrame(getConsultaDeDocumentos());
        } else if (getConsultaDeDocumentos() != null) {
            if (getConsultaDeDocumentos().isClosed()) {
                setConsultaDeDocumentos(new ConsultaDeDocumentos());
                getJdpPrincipal().add(getConsultaDeDocumentos());
                getConsultaDeDocumentos().setVisible(true);
                centralizarJInternalFrame(getConsultaDeDocumentos());
            }
        }
    }//GEN-LAST:event_jmiConsultaDocumentosActionPerformed

    private void jmiEtiquetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEtiquetasActionPerformed
        centralizarLogo(getJlLogo());
        if (getEtiquetaCaixa() == null) {
            setEtiquetaCaixa(new EtiquetaCaixa());
            getJdpPrincipal().add(getEtiquetaCaixa());
            getEtiquetaCaixa().setVisible(true);
            centralizarJInternalFrame(getEtiquetaCaixa());
        } else if (getEtiquetaCaixa() != null) {
            if (getEtiquetaCaixa().isClosed()) {
                setEtiquetaCaixa(new EtiquetaCaixa());
                getJdpPrincipal().add(getEtiquetaCaixa());
                getEtiquetaCaixa().setVisible(true);
                centralizarJInternalFrame(getEtiquetaCaixa());
            }
        }
    }//GEN-LAST:event_jmiEtiquetasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    public javax.swing.JDesktopPane jdpPrincipal;
    private javax.swing.JLabel jlLogo;
    private javax.swing.JMenu jmAdministrarTipoDocumental;
    private javax.swing.JMenu jmCadastrarDocumentos;
    private javax.swing.JMenu jmConfiguracao;
    private javax.swing.JMenu jmConsultas;
    private javax.swing.JMenu jmLogin;
    private javax.swing.JMenu jmRelatorios;
    private javax.swing.JMenuBar jmbMenus;
    private javax.swing.JMenuItem jmiAdministrarUsuários;
    private javax.swing.JMenuItem jmiAlterarSenha;
    private javax.swing.JMenuItem jmiCadastrarDocumentos;
    private javax.swing.JMenuItem jmiCadastrarTipoDocumental;
    private javax.swing.JMenuItem jmiConsultaDocumentos;
    private javax.swing.JMenuItem jmiConsultaTipoDocumental;
    private javax.swing.JMenuItem jmiEditarExcluir;
    private javax.swing.JMenuItem jmiEtiquetas;
    private javax.swing.JMenuItem jmiLogin;
    private javax.swing.JMenuItem jmiSair;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the etiquetaCaixa
     */
    public EtiquetaCaixa getEtiquetaCaixa() {
        return etiquetaCaixa;
    }

    /**
     * @param etiquetaCaixa the etiquetaCaixa to set
     */
    public void setEtiquetaCaixa(EtiquetaCaixa etiquetaCaixa) {
        this.etiquetaCaixa = etiquetaCaixa;
    }

    /**
     * @return the jmRelatorios
     */
    public javax.swing.JMenu getJmRelatorios() {
        return jmRelatorios;
    }

    /**
     * @param jmRelatorios the jmRelatorios to set
     */
    public void setJmRelatorios(javax.swing.JMenu jmRelatorios) {
        this.jmRelatorios = jmRelatorios;
    }

    /**
     * @return the jmiCadastrarDocumentos
     */
    public javax.swing.JMenuItem getJmiCadastrarDocumentos() {
        return jmiCadastrarDocumentos;
    }

    /**
     * @param jmiCadastrarDocumentos the jmiCadastrarDocumentos to set
     */
    public void setJmiCadastrarDocumentos(javax.swing.JMenuItem jmiCadastrarDocumentos) {
        this.jmiCadastrarDocumentos = jmiCadastrarDocumentos;
    }

    /**
     * @return the jmiConsultaDocumentos
     */
    public javax.swing.JMenuItem getJmiConsultaDocumentos() {
        return jmiConsultaDocumentos;
    }

    /**
     * @param jmiConsultaDocumentos the jmiConsultaDocumentos to set
     */
    public void setJmiConsultaDocumentos(javax.swing.JMenuItem jmiConsultaDocumentos) {
        this.jmiConsultaDocumentos = jmiConsultaDocumentos;
    }

    /**
     * @return the jmiConsultaTipoDocumental
     */
    public javax.swing.JMenuItem getJmiConsultaTipoDocumental() {
        return jmiConsultaTipoDocumental;
    }

    /**
     * @param jmiConsultaTipoDocumental the jmiConsultaTipoDocumental to set
     */
    public void setJmiConsultaTipoDocumental(javax.swing.JMenuItem jmiConsultaTipoDocumental) {
        this.jmiConsultaTipoDocumental = jmiConsultaTipoDocumental;
    }

    /**
     * @return the jmiEditarExcluir
     */
    public javax.swing.JMenuItem getJmiEditarExcluir() {
        return jmiEditarExcluir;
    }

    /**
     * @param jmiEditarExcluir the jmiEditarExcluir to set
     */
    public void setJmiEditarExcluir(javax.swing.JMenuItem jmiEditarExcluir) {
        this.jmiEditarExcluir = jmiEditarExcluir;
    }

    /**
     * @return the jmiEtiquetas
     */
    public javax.swing.JMenuItem getJmiEtiquetas() {
        return jmiEtiquetas;
    }

    /**
     * @param jmiEtiquetas the jmiEtiquetas to set
     */
    public void setJmiEtiquetas(javax.swing.JMenuItem jmiEtiquetas) {
        this.jmiEtiquetas = jmiEtiquetas;
    }

    /**
     * @return the consultaDeDocumentos
     */
    public ConsultaDeDocumentos getConsultaDeDocumentos() {
        return consultaDeDocumentos;
    }

    /**
     * @param consultaDeDocumentos the consultaDeDocumentos to set
     */
    public void setConsultaDeDocumentos(ConsultaDeDocumentos consultaDeDocumentos) {
        this.consultaDeDocumentos = consultaDeDocumentos;
    }

    /**
     * @return the cadastroDeDocumentos
     */
    public CadastroDeDocumentos getCadastroDeDocumentos() {
        return cadastroDeDocumentos;
    }

    /**
     * @param cadastroDeDocumentos the cadastroDeDocumentos to set
     */
    public void setCadastroDeDocumentos(CadastroDeDocumentos cadastroDeDocumentos) {
        this.cadastroDeDocumentos = cadastroDeDocumentos;
    }

    /**
     * @return the edicaoExclusaoTipoDocumental
     */
    public EdicaoExclusaoTipoDocumental getEdicaoExclusaoTipoDocumental() {
        return edicaoExclusaoTipoDocumental;
    }

    /**
     * @param edicaoExclusaoTipoDocumental the edicaoExclusaoTipoDocumental to
     * set
     */
    public void setEdicaoExclusaoTipoDocumental(EdicaoExclusaoTipoDocumental edicaoExclusaoTipoDocumental) {
        this.edicaoExclusaoTipoDocumental = edicaoExclusaoTipoDocumental;
    }

    /**
     * @return the consultaTipoDocumental
     */
    public ConsultaTipoDocumental getConsultaTipoDocumental() {
        return consultaTipoDocumental;
    }

    /**
     * @param consultaTipoDocumental the consultaTipoDocumental to set
     */
    public void setConsultaTipoDocumental(ConsultaTipoDocumental consultaTipoDocumental) {
        this.consultaTipoDocumental = consultaTipoDocumental;
    }

    /**
     * @return the cadastroTipoDocumental
     */
    public CadastroTipoDocumental getCadastroTipoDocumental() {
        return cadastroTipoDocumental;
    }

    /**
     * @param cadastroTipoDocumental the cadastroTipoDocumental to set
     */
    public void setCadastroTipoDocumental(CadastroTipoDocumental cadastroTipoDocumental) {
        this.cadastroTipoDocumental = cadastroTipoDocumental;
    }

    /**
     * @return the alterarSenha
     */
    public AlterarSenha getAlterarSenha() {
        return alterarSenha;
    }

    /**
     * @param alterarSenha the alterarSenha to set
     */
    public void setAlterarSenha(AlterarSenha alterarSenha) {
        this.alterarSenha = alterarSenha;
    }

    /**
     * @return the usuarioLogado
     */
    public UsuarioArquivo getUsuarioLogado() {
        return usuarioLogado;
    }

    /**
     * @param usuarioLogado the usuarioLogado to set
     */
    public void setUsuarioLogado(UsuarioArquivo usuarioLogado) {
        this.usuarioLogado = usuarioLogado;
    }

    /**
     * @return the administrarUsuarios
     */
    public AdministrarUsuarios getAdministrarUsuarios() {
        return administrarUsuarios;
    }

    /**
     * @param administrarUsuarios the administrarUsuarios to set
     */
    public void setAdministrarUsuarios(AdministrarUsuarios administrarUsuarios) {
        this.administrarUsuarios = administrarUsuarios;
    }

    /**
     * @return the jdpPrincipal
     */
    public javax.swing.JDesktopPane getJdpPrincipal() {
        return jdpPrincipal;
    }

    /**
     * @param jdpPrincipal the jdpPrincipal to set
     */
    public void setJdpPrincipal(javax.swing.JDesktopPane jdpPrincipal) {
        this.jdpPrincipal = jdpPrincipal;
    }

    /**
     * @return the jmbMenus
     */
    public javax.swing.JMenuBar getJmbMenus() {
        return jmbMenus;
    }

    /**
     * @param jmbMenus the jmbMenus to set
     */
    public void setJmbMenus(javax.swing.JMenuBar jmbMenus) {
        this.jmbMenus = jmbMenus;
    }

    /**
     * @return the jmConfiguracao
     */
    public javax.swing.JMenu getJmConfiguracao() {
        return jmConfiguracao;
    }

    /**
     * @param jmConfiguracao the jmConfiguracao to set
     */
    public void setJmConfiguracao(javax.swing.JMenu jmConfiguracao) {
        this.jmConfiguracao = jmConfiguracao;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @param jScrollPane1 the jScrollPane1 to set
     */
    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    /**
     * @return the jTree1
     */
    public javax.swing.JTree getjTree1() {
        return jTree1;
    }

    /**
     * @param jTree1 the jTree1 to set
     */
    public void setjTree1(javax.swing.JTree jTree1) {
        this.jTree1 = jTree1;
    }

    /**
     * @return the telaLogin
     */
    public TelaDeLogin getTelaLogin() {
        return telaLogin;
    }

    /**
     * @param telaLogin the telaLogin to set
     */
    public void setTelaLogin(TelaDeLogin telaLogin) {
        this.telaLogin = telaLogin;
    }

    /**
     * @return the jlLogo
     */
    public javax.swing.JLabel getJlLogo() {
        return jlLogo;
    }

    /**
     * @param jlLogo the jlLogo to set
     */
    public void setJlLogo(javax.swing.JLabel jlLogo) {
        this.jlLogo = jlLogo;
    }

    /**
     * @return the jmCadastrarDocumentos
     */
    public javax.swing.JMenu getJmCadastrarDocumentos() {
        return jmCadastrarDocumentos;
    }

    /**
     * @param jmCadastrarDocumentos the jmCadastrarDocumentos to set
     */
    public void setJmCadastrarDocumentos(javax.swing.JMenu jmCadastrarDocumentos) {
        this.jmCadastrarDocumentos = jmCadastrarDocumentos;
    }

    /**
     * @return the jmConsultas
     */
    public javax.swing.JMenu getJmConsultas() {
        return jmConsultas;
    }

    /**
     * @param jmConsultas the jmConsultas to set
     */
    public void setJmConsultas(javax.swing.JMenu jmConsultas) {
        this.jmConsultas = jmConsultas;
    }

    /**
     * @return the jmLogin
     */
    public javax.swing.JMenu getJmLogin() {
        return jmLogin;
    }

    /**
     * @param jmLogin the jmLogin to set
     */
    public void setJmLogin(javax.swing.JMenu jmLogin) {
        this.jmLogin = jmLogin;
    }

    /**
     * @return the jmiAdministrarUsuários
     */
    public javax.swing.JMenuItem getJmiAdministrarUsuários() {
        return jmiAdministrarUsuários;
    }

    /**
     * @param jmiAdministrarUsuários the jmiAdministrarUsuários to set
     */
    public void setJmiAdministrarUsuários(javax.swing.JMenuItem jmiAdministrarUsuários) {
        this.jmiAdministrarUsuários = jmiAdministrarUsuários;
    }

    /**
     * @return the jmiLogin
     */
    public javax.swing.JMenuItem getJmiLogin() {
        return jmiLogin;
    }

    /**
     * @param jmiLogin the jmiLogin to set
     */
    public void setJmiLogin(javax.swing.JMenuItem jmiLogin) {
        this.jmiLogin = jmiLogin;
    }

    /**
     * @return the jmiSair
     */
    public javax.swing.JMenuItem getJmiSair() {
        return jmiSair;
    }

    /**
     * @param jmiSair the jmiSair to set
     */
    public void setJmiSair(javax.swing.JMenuItem jmiSair) {
        this.jmiSair = jmiSair;
    }

    /**
     * @return the jmiAlterarSenha
     */
    public javax.swing.JMenuItem getJmiAlterarSenha() {
        return jmiAlterarSenha;
    }

    /**
     * @param jmiAlterarSenha the jmiAlterarSenha to set
     */
    public void setJmiAlterarSenha(javax.swing.JMenuItem jmiAlterarSenha) {
        this.jmiAlterarSenha = jmiAlterarSenha;
    }

    /**
     * @return the jmiCadastrarTipoDocumental
     */
    public javax.swing.JMenuItem getJmiCadastrarTipoDocumental() {
        return jmiCadastrarTipoDocumental;
    }

    /**
     * @param jmiCadastrarTipoDocumental the jmiCadastrarTipoDocumental to set
     */
    public void setJmiCadastrarTipoDocumental(javax.swing.JMenuItem jmiCadastrarTipoDocumental) {
        this.jmiCadastrarTipoDocumental = jmiCadastrarTipoDocumental;
    }

    /**
     * @return the jmAdministrarTipoDocumental
     */
    public javax.swing.JMenu getJmAdministrarTipoDocumental() {
        return jmAdministrarTipoDocumental;
    }

    /**
     * @param jmAdministrarTipoDocumental the jmAdministrarTipoDocumental to set
     */
    public void setJmAdministrarTipoDocumental(javax.swing.JMenu jmAdministrarTipoDocumental) {
        this.jmAdministrarTipoDocumental = jmAdministrarTipoDocumental;
    }
}
