package br.com.sicoob_credinova.arquivo_prejuizo_uad.view.usuarios;

import br.com.sicoob_credinova.arquivo_prejuizo_uad.controller.UsuarioController;
import br.com.sicoob_credinova.arquivo_prejuizo_uad.model.UsuarioArquivo;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Alisson Jaques
 */
public class AlterarSenha extends javax.swing.JInternalFrame {

    private UsuarioArquivo usuarioLogado;
    private UsuarioController controle;

    /**
     * Creates new form AlterarSenha
     *
     * @param usuarioLogado o usuário logado no sistema
     */
    public AlterarSenha(UsuarioArquivo usuarioLogado) {
        this.setFrameIcon(new ImageIcon("src\\br\\com\\sicoob_credinova\\arquivo_prejuizo_uad\\img\\arquivo.png"));
        initComponents();
        this.usuarioLogado = usuarioLogado;
        this.controle = new UsuarioController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlSenhaAtual = new javax.swing.JLabel();
        jlNovaSenha = new javax.swing.JLabel();
        jlRepetirNovaSenha = new javax.swing.JLabel();
        jbAlterar = new javax.swing.JButton();
        jtfSenhaAtual = new javax.swing.JPasswordField();
        jtfNovaSenha = new javax.swing.JPasswordField();
        jtfRepetirNovaSenha = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(72, 61, 139));
        setClosable(true);
        setIconifiable(true);
        setTitle("Alterar Senha");

        jlSenhaAtual.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlSenhaAtual.setText("Senha atual:");

        jlNovaSenha.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlNovaSenha.setText("Nova senha:");

        jlRepetirNovaSenha.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlRepetirNovaSenha.setText("Repetir nova senha:");

        jbAlterar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sicoob_credinova/arquivo_prejuizo_uad/img/edit_16.png"))); // NOI18N
        jbAlterar.setText("Alterar Senha");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });
        jbAlterar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbAlterarKeyPressed(evt);
            }
        });

        jtfSenhaAtual.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        jtfNovaSenha.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        jtfRepetirNovaSenha.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jbAlterar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNovaSenha)
                            .addComponent(jlRepetirNovaSenha)
                            .addComponent(jlSenhaAtual))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfSenhaAtual)
                            .addComponent(jtfRepetirNovaSenha)
                            .addComponent(jtfNovaSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSenhaAtual)
                    .addComponent(jtfSenhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNovaSenha)
                    .addComponent(jtfNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlRepetirNovaSenha)
                    .addComponent(jtfRepetirNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jbAlterar)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Verifica se existe campos vazios no formulário da tela.
     *
     * @return true se existir campos vazios, false caso contrário.
     */
    private boolean verificaCamposVazios() {
        return getJtfSenhaAtual().getText().equals("") || getJtfNovaSenha().getText().equals("")
                || getJtfRepetirNovaSenha().getText().equals("");
    }

    private void acaoAlterarSenha() {
        if (verificaCamposVazios()) {
            JOptionPane.showMessageDialog(this, "Existem campos vazios, preencha "
                    + "todos os campos para continuar", "Alerta", 2);
        } else {
            if (getJtfSenhaAtual().getText().equals(getUsuarioLogado().getSenha())) {
                if (getJtfNovaSenha().getText().equals(getJtfRepetirNovaSenha().getText())) {
                    getUsuarioLogado().setSenha(getJtfNovaSenha().getText());
                    getControle().editar(getUsuarioLogado());
                    JOptionPane.showMessageDialog(this, "Senha alterada com sucesso!", "Alerta", 2);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "A nova senha e sua confirmação não estão iguais!", "Alerta", 2);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Senha atual inválida!", "Alerta", 2);
            }
        }
    }

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        acaoAlterarSenha();
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jbAlterarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbAlterarKeyPressed
        acaoAlterarSenha();
    }//GEN-LAST:event_jbAlterarKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JLabel jlNovaSenha;
    private javax.swing.JLabel jlRepetirNovaSenha;
    private javax.swing.JLabel jlSenhaAtual;
    private javax.swing.JPasswordField jtfNovaSenha;
    private javax.swing.JPasswordField jtfRepetirNovaSenha;
    private javax.swing.JPasswordField jtfSenhaAtual;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the controle
     */
    public UsuarioController getControle() {
        return controle;
    }

    /**
     * @param controle the controle to set
     */
    public void setControle(UsuarioController controle) {
        this.controle = controle;
    }

    /**
     * @return the usuarioLogado
     */
    public UsuarioArquivo getUsuarioLogado() {
        return usuarioLogado;
    }

    /**
     * @param usuarioLogado the usuarioLogado to set
     */
    public void setUsuarioLogado(UsuarioArquivo usuarioLogado) {
        this.usuarioLogado = usuarioLogado;
    }

    /**
     * @return the jPanel1
     */
    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    /**
     * @param jPanel1 the jPanel1 to set
     */
    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    /**
     * @return the jbAlterar
     */
    public javax.swing.JButton getJbAlterar() {
        return jbAlterar;
    }

    /**
     * @param jbAlterar the jbAlterar to set
     */
    public void setJbAlterar(javax.swing.JButton jbAlterar) {
        this.jbAlterar = jbAlterar;
    }

    /**
     * @return the jlNovaSenha
     */
    public javax.swing.JLabel getJlNovaSenha() {
        return jlNovaSenha;
    }

    /**
     * @param jlNovaSenha the jlNovaSenha to set
     */
    public void setJlNovaSenha(javax.swing.JLabel jlNovaSenha) {
        this.jlNovaSenha = jlNovaSenha;
    }

    /**
     * @return the jlRepetirNovaSenha
     */
    public javax.swing.JLabel getJlRepetirNovaSenha() {
        return jlRepetirNovaSenha;
    }

    /**
     * @param jlRepetirNovaSenha the jlRepetirNovaSenha to set
     */
    public void setJlRepetirNovaSenha(javax.swing.JLabel jlRepetirNovaSenha) {
        this.jlRepetirNovaSenha = jlRepetirNovaSenha;
    }

    /**
     * @return the jlSenhaAtual
     */
    public javax.swing.JLabel getJlSenhaAtual() {
        return jlSenhaAtual;
    }

    /**
     * @param jlSenhaAtual the jlSenhaAtual to set
     */
    public void setJlSenhaAtual(javax.swing.JLabel jlSenhaAtual) {
        this.jlSenhaAtual = jlSenhaAtual;
    }

    /**
     * @return the jtfNovaSenha
     */
    public javax.swing.JPasswordField getJtfNovaSenha() {
        return jtfNovaSenha;
    }

    /**
     * @param jtfNovaSenha the jtfNovaSenha to set
     */
    public void setJtfNovaSenha(javax.swing.JPasswordField jtfNovaSenha) {
        this.jtfNovaSenha = jtfNovaSenha;
    }

    /**
     * @return the jtfRepetirNovaSenha
     */
    public javax.swing.JPasswordField getJtfRepetirNovaSenha() {
        return jtfRepetirNovaSenha;
    }

    /**
     * @param jtfRepetirNovaSenha the jtfRepetirNovaSenha to set
     */
    public void setJtfRepetirNovaSenha(javax.swing.JPasswordField jtfRepetirNovaSenha) {
        this.jtfRepetirNovaSenha = jtfRepetirNovaSenha;
    }

    /**
     * @return the jtfSenhaAtual
     */
    public javax.swing.JPasswordField getJtfSenhaAtual() {
        return jtfSenhaAtual;
    }

    /**
     * @param jtfSenhaAtual the jtfSenhaAtual to set
     */
    public void setJtfSenhaAtual(javax.swing.JPasswordField jtfSenhaAtual) {
        this.jtfSenhaAtual = jtfSenhaAtual;
    }
}
