package br.com.sicoob_credinova.arquivo_prejuizo_uad.view.usuarios;

import br.com.sicoob_credinova.arquivo_prejuizo_uad.controller.UsuarioController;
import br.com.sicoob_credinova.arquivo_prejuizo_uad.enums.Perfil;
import br.com.sicoob_credinova.arquivo_prejuizo_uad.model.UsuarioArquivo;
import br.com.sicoob_credinova.arquivo_prejuizo_uad.utils.GeraCpfCnpj;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Alisson Jaques
 */
public class CadastrarNovoUsuario extends javax.swing.JFrame {

    private AdministrarUsuarios administrarUsuarios;

    /**
     * Creates new form CadastrarNovoUsuario
     *
     * @param administrarUsuarios
     */
    public CadastrarNovoUsuario(AdministrarUsuarios administrarUsuarios) {
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("src\\br\\com\\sicoob_credinova\\arquivo_prejuizo_uad\\img\\faviconP.png"));
        initComponents();
        this.administrarUsuarios = administrarUsuarios;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlNome = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jlUsuario = new javax.swing.JLabel();
        jftUsuario = new javax.swing.JTextField();
        jftCpf = new javax.swing.JFormattedTextField();
        jlCpf = new javax.swing.JLabel();
        jlSenha = new javax.swing.JLabel();
        jftSenha = new javax.swing.JTextField();
        jlConfirmarSenha = new javax.swing.JLabel();
        jftConfirmarSenha = new javax.swing.JTextField();
        jlPerfil = new javax.swing.JLabel();
        jcbPerfil = new javax.swing.JComboBox<>();
        jbCriar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Novo Usuário");
        setBackground(new java.awt.Color(0, 128, 128));

        jlNome.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlNome.setText("Nome Completo:");

        jtfNome.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jlUsuario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlUsuario.setText("Login Sisbr:");

        jftUsuario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        try {
            jftCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftCpf.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jftCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jftCpfFocusLost(evt);
            }
        });

        jlCpf.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlCpf.setText("CPF:");

        jlSenha.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlSenha.setText("Senha:");

        jftSenha.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jlConfirmarSenha.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlConfirmarSenha.setText("Confirmar Senha:");

        jftConfirmarSenha.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jlPerfil.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlPerfil.setText("Perfil:");

        jcbPerfil.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jcbPerfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuário", "Supervisor", "Administrador" }));
        jcbPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPerfilActionPerformed(evt);
            }
        });

        jbCriar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jbCriar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sicoob_credinova/arquivo_prejuizo_uad/img/add_16.png"))); // NOI18N
        jbCriar.setText("Criar Novo Usuário");
        jbCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCriarActionPerformed(evt);
            }
        });
        jbCriar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbCriarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jlConfirmarSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlCpf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jlPerfil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jftUsuario)
                    .addComponent(jtfNome)
                    .addComponent(jftSenha)
                    .addComponent(jftConfirmarSenha)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jftCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addComponent(jbCriar)
                .addGap(149, 149, 149))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNome)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlUsuario)
                    .addComponent(jftUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jftCpf)
                    .addComponent(jlCpf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSenha)
                    .addComponent(jftSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlConfirmarSenha)
                    .addComponent(jftConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPerfil)
                    .addComponent(jcbPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jbCriar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jftCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftCpfFocusLost
        if(!GeraCpfCnpj.validarCpf(getJftCpf().getText()) || getJftCpf().getText().equals("  .   .   -  ")){
            JOptionPane.showMessageDialog(this, "CPF informado não é válido, insira um CPF válido!", "Alerta", 2);
            getJftCpf().requestFocus();
        }
    }//GEN-LAST:event_jftCpfFocusLost
    
    /**
     * Verifica se os campos da tela estão vazios.
     * @return true se os campos da tela estiverem vazios, false caso contrário
     */
    private boolean verificaCampos(){
        return getJtfNome().getText().equals("") || getJftUsuario().getText().equals("")
                || getJftCpf().getText().equals("   .   .   -  ")
                || getJftSenha().getText().equals("")
                || getJftConfirmarSenha().getText().equals("");
    }
    
    /**
     * Verifica se as duas senhas passadas como argumentos são iguais.
     * @return true se as senhas passadas como argumentos forem iguais, false caso contrário
     */
    private boolean verificaSenhas(String senha, String senhaConfirmacao){
        return senha.equals(senhaConfirmacao);
    }
    
    private void acaoCriarUsuario(){
        if(verificaCampos()){
            JOptionPane.showMessageDialog(this, "Existem campos vazios, favor preencher todos os campos para cadastrar o usuário!", "Alerta", 2);
        } else{
            if(verificaSenhas(getJftSenha().getText(),getJftConfirmarSenha().getText())){
                UsuarioController controle = new UsuarioController();
                Boolean existeUsuario = controle.verificaUsuarioBancoNomeUsuario(getJftUsuario().getText());
                if(existeUsuario){
                    JOptionPane.showMessageDialog(this, "Já existe usuário cadastrado com o nome de login informado!", "Alerta", 2);
                } else{
                    existeUsuario = controle.verificaUsuarioBancoCpf(getJftCpf().getText());
                    if(existeUsuario){
                        JOptionPane.showMessageDialog(this, "Já existe usuário cadastrado com o cpf informado!", "Alerta", 2);
                    }else{
                        Perfil perfil = Perfil.USUARIO;
                        if(getJcbPerfil().getSelectedIndex()==1){
                            perfil = Perfil.SUPERVISOR;
                        } else if(getJcbPerfil().getSelectedIndex()==2){
                            perfil = Perfil.ADMINISTRADOR;
                        }
                        controle.inserir(new UsuarioArquivo(1,getJtfNome().getText(),getJftUsuario().getText(),
                        getJftCpf().getText(),getJftSenha().getText(),perfil));
                        this.administrarUsuarios.popularTabela();
                        JOptionPane.showMessageDialog(this, "Usuário cadastrado com sucesso!", "Alerta", 2);
                        dispose();
                    }
                }
            } else{
                JOptionPane.showMessageDialog(this, "A senha e sua confirmação não estão iguais, elas devem ser idênticas!", "Alerta", 2);
            }
        }
    }
    
    private void jbCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCriarActionPerformed
        acaoCriarUsuario();
    }//GEN-LAST:event_jbCriarActionPerformed

    private void jbCriarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbCriarKeyPressed
        acaoCriarUsuario();
    }//GEN-LAST:event_jbCriarKeyPressed

    private void jcbPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbPerfilActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbCriar;
    private javax.swing.JComboBox<String> jcbPerfil;
    private javax.swing.JTextField jftConfirmarSenha;
    private javax.swing.JFormattedTextField jftCpf;
    private javax.swing.JTextField jftSenha;
    private javax.swing.JTextField jftUsuario;
    private javax.swing.JLabel jlConfirmarSenha;
    private javax.swing.JLabel jlCpf;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlPerfil;
    private javax.swing.JLabel jlSenha;
    private javax.swing.JLabel jlUsuario;
    private javax.swing.JTextField jtfNome;
    // End of variables declaration//GEN-END:variables
      /**
     * @return the administrarUsuarios
     */
    public AdministrarUsuarios getAdministrarUsuarios() {
        return administrarUsuarios;
    }

    /**
     * @param administrarUsuarios the administrarUsuarios to set
     */
    public void setAdministrarUsuarios(AdministrarUsuarios administrarUsuarios) {
        this.administrarUsuarios = administrarUsuarios;
    }

    /**
     * @return the jPanel1
     */
    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    /**
     * @param jPanel1 the jPanel1 to set
     */
    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    /**
     * @return the jftCpf
     */
    public javax.swing.JFormattedTextField getJftCpf() {
        return jftCpf;
    }

    /**
     * @param jftCpf the jftCpf to set
     */
    public void setJftCpf(javax.swing.JFormattedTextField jftCpf) {
        this.jftCpf = jftCpf;
    }

    /**
     * @return the jftUsuario
     */
    public javax.swing.JTextField getJftUsuario() {
        return jftUsuario;
    }

    /**
     * @param jftUsuario the jftUsuario to set
     */
    public void setJftUsuario(javax.swing.JTextField jftUsuario) {
        this.jftUsuario = jftUsuario;
    }

    /**
     * @return the jlCpf
     */
    public javax.swing.JLabel getJlCpf() {
        return jlCpf;
    }

    /**
     * @param jlCpf the jlCpf to set
     */
    public void setJlCpf(javax.swing.JLabel jlCpf) {
        this.jlCpf = jlCpf;
    }

    /**
     * @return the jlNome
     */
    public javax.swing.JLabel getJlNome() {
        return jlNome;
    }

    /**
     * @param jlNome the jlNome to set
     */
    public void setJlNome(javax.swing.JLabel jlNome) {
        this.jlNome = jlNome;
    }

    /**
     * @return the jlUsuario
     */
    public javax.swing.JLabel getJlUsuario() {
        return jlUsuario;
    }

    /**
     * @param jlUsuario the jlUsuario to set
     */
    public void setJlUsuario(javax.swing.JLabel jlUsuario) {
        this.jlUsuario = jlUsuario;
    }

    /**
     * @return the jtfNome
     */
    public javax.swing.JTextField getJtfNome() {
        return jtfNome;
    }

    /**
     * @param jtfNome the jtfNome to set
     */
    public void setJtfNome(javax.swing.JTextField jtfNome) {
        this.jtfNome = jtfNome;
    }

    /**
     * @return the jbCriar
     */
    public javax.swing.JButton getJbCriar() {
        return jbCriar;
    }

    /**
     * @param jbCriar the jbCriar to set
     */
    public void setJbCriar(javax.swing.JButton jbCriar) {
        this.jbCriar = jbCriar;
    }

    /**
     * @return the jcbPerfil
     */
    public javax.swing.JComboBox<String> getJcbPerfil() {
        return jcbPerfil;
    }

    /**
     * @param jcbPerfil the jcbPerfil to set
     */
    public void setJcbPerfil(javax.swing.JComboBox<String> jcbPerfil) {
        this.jcbPerfil = jcbPerfil;
    }

    /**
     * @return the jftConfirmarSenha
     */
    public javax.swing.JTextField getJftConfirmarSenha() {
        return jftConfirmarSenha;
    }

    /**
     * @param jftConfirmarSenha the jftConfirmarSenha to set
     */
    public void setJftConfirmarSenha(javax.swing.JTextField jftConfirmarSenha) {
        this.jftConfirmarSenha = jftConfirmarSenha;
    }

    /**
     * @return the jftSenha
     */
    public javax.swing.JTextField getJftSenha() {
        return jftSenha;
    }

    /**
     * @param jftSenha the jftSenha to set
     */
    public void setJftSenha(javax.swing.JTextField jftSenha) {
        this.jftSenha = jftSenha;
    }

    /**
     * @return the jlConfirmarSenha
     */
    public javax.swing.JLabel getJlConfirmarSenha() {
        return jlConfirmarSenha;
    }

    /**
     * @param jlConfirmarSenha the jlConfirmarSenha to set
     */
    public void setJlConfirmarSenha(javax.swing.JLabel jlConfirmarSenha) {
        this.jlConfirmarSenha = jlConfirmarSenha;
    }

    /**
     * @return the jlPerfil
     */
    public javax.swing.JLabel getJlPerfil() {
        return jlPerfil;
    }

    /**
     * @param jlPerfil the jlPerfil to set
     */
    public void setJlPerfil(javax.swing.JLabel jlPerfil) {
        this.jlPerfil = jlPerfil;
    }

    /**
     * @return the jlSenha
     */
    public javax.swing.JLabel getJlSenha() {
        return jlSenha;
    }

    /**
     * @param jlSenha the jlSenha to set
     */
    public void setJlSenha(javax.swing.JLabel jlSenha) {
        this.jlSenha = jlSenha;
    }
}
