package br.com.sicoob_credinova.arquivo_prejuizo_uad.view.relatorios;

import br.com.sicoob_credinova.arquivo_prejuizo_uad.dao.RelatorioDAO;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author Alisson Jaques
 */
public class EtiquetaCaixa extends javax.swing.JInternalFrame {

    /**
     * Creates new form EtiquetaCaixa
     */
    public EtiquetaCaixa() {
        this.setFrameIcon(new ImageIcon("src\\br\\com\\sicoob_credinova\\arquivo_prejuizo_uad\\img\\arquivo.png"));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlCaixaInicial = new javax.swing.JLabel();
        jtfCaixaInicial = new javax.swing.JTextField();
        jlCaixaFinal = new javax.swing.JLabel();
        jtfCaixaFinal = new javax.swing.JTextField();
        jbGerarEtiquetas = new javax.swing.JButton();

        setBackground(new java.awt.Color(72, 61, 139));
        setClosable(true);
        setIconifiable(true);
        setTitle("Etiquetas para Caixas");

        jlCaixaInicial.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlCaixaInicial.setText("Caixa Inicial:");

        jtfCaixaInicial.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jlCaixaFinal.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlCaixaFinal.setText("Caixa Final:");

        jtfCaixaFinal.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jbGerarEtiquetas.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jbGerarEtiquetas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sicoob_credinova/arquivo_prejuizo_uad/img/ico_pdf.png"))); // NOI18N
        jbGerarEtiquetas.setText("Gerar Etiquetas");
        jbGerarEtiquetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGerarEtiquetasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlCaixaInicial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfCaixaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jlCaixaFinal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfCaixaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jbGerarEtiquetas)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCaixaInicial)
                    .addComponent(jtfCaixaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCaixaFinal)
                    .addComponent(jtfCaixaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbGerarEtiquetas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void acaoGerarEtiquetas(){
        try{
            int caixaInicial = Integer.parseInt(getJtfCaixaInicial().getText());
            int caixaFinal = Integer.parseInt(getJtfCaixaFinal().getText());
            
            List<String> parametros = new ArrayList();
            List<String> valores = new ArrayList();
            parametros.add("inicio");
            parametros.add("fim");
            valores.add(String.valueOf(caixaInicial));
            valores.add(String.valueOf(caixaFinal));
            try {
                RelatorioDAO.gerarRelatorio("etiquetaCaixas", parametros, valores);
            } catch (IOException | JRException ex) {
                JOptionPane.showMessageDialog(this, "Erro ao gerar relatório! Erro: " + ex.getMessage(), "Alerta", 2);
            }
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Número da caixa inválido, forneça um número inteiro válido! Erro: " + e.getMessage(), "Alerta", 2);
        }
    }
    
    private void jbGerarEtiquetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGerarEtiquetasActionPerformed
        acaoGerarEtiquetas();
    }//GEN-LAST:event_jbGerarEtiquetasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbGerarEtiquetas;
    private javax.swing.JLabel jlCaixaFinal;
    private javax.swing.JLabel jlCaixaInicial;
    private javax.swing.JTextField jtfCaixaFinal;
    private javax.swing.JTextField jtfCaixaInicial;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jPanel1
     */
    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    /**
     * @param jPanel1 the jPanel1 to set
     */
    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    /**
     * @return the jbGerarEtiquetas
     */
    public javax.swing.JButton getJbGerarEtiquetas() {
        return jbGerarEtiquetas;
    }

    /**
     * @param jbGerarEtiquetas the jbGerarEtiquetas to set
     */
    public void setJbGerarEtiquetas(javax.swing.JButton jbGerarEtiquetas) {
        this.jbGerarEtiquetas = jbGerarEtiquetas;
    }

    /**
     * @return the jlCaixaFinal
     */
    public javax.swing.JLabel getJlCaixaFinal() {
        return jlCaixaFinal;
    }

    /**
     * @param jlCaixaFinal the jlCaixaFinal to set
     */
    public void setJlCaixaFinal(javax.swing.JLabel jlCaixaFinal) {
        this.jlCaixaFinal = jlCaixaFinal;
    }

    /**
     * @return the jlCaixaInicial
     */
    public javax.swing.JLabel getJlCaixaInicial() {
        return jlCaixaInicial;
    }

    /**
     * @param jlCaixaInicial the jlCaixaInicial to set
     */
    public void setJlCaixaInicial(javax.swing.JLabel jlCaixaInicial) {
        this.jlCaixaInicial = jlCaixaInicial;
    }

    /**
     * @return the jtfCaixaFinal
     */
    public javax.swing.JTextField getJtfCaixaFinal() {
        return jtfCaixaFinal;
    }

    /**
     * @param jtfCaixaFinal the jtfCaixaFinal to set
     */
    public void setJtfCaixaFinal(javax.swing.JTextField jtfCaixaFinal) {
        this.jtfCaixaFinal = jtfCaixaFinal;
    }

    /**
     * @return the jtfCaixaInicial
     */
    public javax.swing.JTextField getJtfCaixaInicial() {
        return jtfCaixaInicial;
    }

    /**
     * @param jtfCaixaInicial the jtfCaixaInicial to set
     */
    public void setJtfCaixaInicial(javax.swing.JTextField jtfCaixaInicial) {
        this.jtfCaixaInicial = jtfCaixaInicial;
    }
}
