package br.com.aj_sistemas.novo_sgad.view.login;

import br.com.aj_sistemas.novo_sgad.controller.UsuarioController;
import br.com.aj_sistemas.novo_sgad.model.UsuarioArquivo;
import br.com.aj_sistemas.novo_sgad.utils.BibliotecaArquivoDeslizante;
import br.com.aj_sistemas.novo_sgad.view.principal.TelaPrincipal;
import javax.swing.JOptionPane;
import org.mindrot.jbcrypt.BCrypt;

/**
 * A classe TelaDeLogin representa uma tela de login que permite que o usuï¿½rio
 * entre ou nï¿½o no sistema (para ter acesso ele deve digitar credenciais
 * vï¿½lidas).
 *
 * @author Alisson
 */
public class TelaDeLogin extends javax.swing.JDialog { // declaraï¿½ï¿½o da classe

    /*
    * Campos da classe
     */
    private TelaPrincipal tp;
    private UsuarioArquivo usuarioLogado;

    /**
     * Creates new form TelaDeLogin
     *
     * @param parent
     * @param modal
     * @param usuarioLogado
     */
    public TelaDeLogin(java.awt.Frame parent, boolean modal, UsuarioArquivo usuarioLogado) {
        super(parent, modal);
        initComponents();
        tp = (TelaPrincipal) parent;
        this.usuarioLogado = usuarioLogado;
        acionaComEnter();
    }

    private void acionaComEnter() {
        getRootPane().setDefaultButton(getBtnConfirmar());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pLogin = new javax.swing.JPanel();
        lTitulo = new javax.swing.JLabel();
        lUsuario = new javax.swing.JLabel();
        lSenha = new javax.swing.JLabel();
        pfSenha = new javax.swing.JPasswordField();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        tfUsuario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Login");

        lTitulo.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        lTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/aj_sistemas/novo_sgad/img/arquivoDeslizanteLogo.png"))); // NOI18N
        lTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lUsuario.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        lUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/aj_sistemas/novo_sgad/img/user32.png"))); // NOI18N
        lUsuario.setText("Usuário:");

        lSenha.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        lSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/aj_sistemas/novo_sgad/img/lock_32.png"))); // NOI18N
        lSenha.setText("Senha:");

        pfSenha.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N

        btnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/aj_sistemas/novo_sgad/img/ico_processado.png"))); // NOI18N
        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/aj_sistemas/novo_sgad/img/Cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        tfUsuario.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N

        javax.swing.GroupLayout pLoginLayout = new javax.swing.GroupLayout(pLogin);
        pLogin.setLayout(pLoginLayout);
        pLoginLayout.setHorizontalGroup(
            pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pLoginLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lUsuario)
                    .addComponent(lSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pLoginLayout.createSequentialGroup()
                        .addComponent(btnConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar))
                    .addComponent(tfUsuario)
                    .addComponent(pfSenha))
                .addGap(103, 103, 103))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        pLoginLayout.setVerticalGroup(
            pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lUsuario)
                    .addComponent(tfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lSenha)
                    .addComponent(pfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        String nome = getTfUsuario().getText();
        String senha = String.valueOf(getPfSenha().getPassword());
        UsuarioController controle = new UsuarioController();
        UsuarioArquivo usuario = controle.consultarPorNome(nome);
        if (usuario == null) {
            JOptionPane.showMessageDialog(this, "Nome de usuário inválido!", "Erro ao Logar no sistema", JOptionPane.INFORMATION_MESSAGE);
        } else if (BCrypt.checkpw(senha, usuario.getSenha())) {
            getTp().getJmCadastrarDocumentos().setEnabled(true);
            getTp().getJmConfiguracao().setEnabled(true);
            getTp().getJmConsultas().setEnabled(true);
            getTp().getJmRelatorios().setEnabled(true);
            if (null != usuario.getPerfil()) {
                switch (usuario.getPerfil()) {
                    case ADMINISTRADOR:
                        getTp().getJmiAdministrarUsuários().setEnabled(true);
                        break;
                    case SUPERVISOR:
                        getTp().getJmiAdministrarUsuários().setEnabled(false);
                        break;
                    case USUARIO:
                        getTp().getJmiAdministrarUsuários().setEnabled(false);
                        getTp().getJmAdministrarTipoDocumental().setEnabled(false);
                        break;
                    default:
                        break;
                }
            }

            getTp().getJmiLogin().setEnabled(false);
            BibliotecaArquivoDeslizante.copiaUsuario(getUsuarioLogado(), usuario);

            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Senha inválida!", "Erro ao Logar no sistema", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel lSenha;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JLabel lUsuario;
    private javax.swing.JPanel pLogin;
    private javax.swing.JPasswordField pfSenha;
    private javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the usuarioLogado
     */
    public UsuarioArquivo getUsuarioLogado() {
        return usuarioLogado;
    }

    /**
     * @param usuarioLogado the usuarioLogado to set
     */
    public void setUsuarioLogado(UsuarioArquivo usuarioLogado) {
        this.usuarioLogado = usuarioLogado;
    }

    /**
     * @return the tp
     */
    public TelaPrincipal getTp() {
        return tp;
    }

    /**
     * @param tp the tp to set
     */
    public void setTp(TelaPrincipal tp) {
        this.tp = tp;
    }

    /**
     * @return the btnCancelar
     */
    public javax.swing.JButton getBtnCancelar() {
        return btnCancelar;
    }

    /**
     * @param btnCancelar the btnCancelar to set
     */
    public void setBtnCancelar(javax.swing.JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }

    /**
     * @return the btnConfirmar
     */
    public javax.swing.JButton getBtnConfirmar() {
        return btnConfirmar;
    }

    /**
     * @param btnConfirmar the btnConfirmar to set
     */
    public void setBtnConfirmar(javax.swing.JButton btnConfirmar) {
        this.btnConfirmar = btnConfirmar;
    }

    /**
     * @return the lSenha
     */
    public javax.swing.JLabel getlSenha() {
        return lSenha;
    }

    /**
     * @param lSenha the lSenha to set
     */
    public void setlSenha(javax.swing.JLabel lSenha) {
        this.lSenha = lSenha;
    }

    /**
     * @return the lTitulo
     */
    public javax.swing.JLabel getlTitulo() {
        return lTitulo;
    }

    /**
     * @param lTitulo the lTitulo to set
     */
    public void setlTitulo(javax.swing.JLabel lTitulo) {
        this.lTitulo = lTitulo;
    }

    /**
     * @return the lUsuario
     */
    public javax.swing.JLabel getlUsuario() {
        return lUsuario;
    }

    /**
     * @param lUsuario the lUsuario to set
     */
    public void setlUsuario(javax.swing.JLabel lUsuario) {
        this.lUsuario = lUsuario;
    }

    /**
     * @return the pLogin
     */
    public javax.swing.JPanel getpLogin() {
        return pLogin;
    }

    /**
     * @param pLogin the pLogin to set
     */
    public void setpLogin(javax.swing.JPanel pLogin) {
        this.pLogin = pLogin;
    }

    /**
     * @return the pfSenha
     */
    public javax.swing.JPasswordField getPfSenha() {
        return pfSenha;
    }

    /**
     * @param pfSenha the pfSenha to set
     */
    public void setPfSenha(javax.swing.JPasswordField pfSenha) {
        this.pfSenha = pfSenha;
    }

    /**
     * @return the tfUsuario
     */
    public javax.swing.JTextField getTfUsuario() {
        return tfUsuario;
    }

    /**
     * @param tfUsuario the tfUsuario to set
     */
    public void setTfUsuario(javax.swing.JTextField tfUsuario) {
        this.tfUsuario = tfUsuario;
    }
}
